// Catalogue de démonstration (AUDIT §71) : 50 comptes vendeurs fictifs. Numéros dans la plage ARCEP réservée à la
// fiction (06 39 98 XX XX, jamais attribuée), e-mails à étiquette « + » sur la boîte du propriétaire, mots de passe générés
// par le serveur à la création et remis une seule fois à l'administrateur (jamais dans ce dépôt).
const CITIES = {
  paris11: { city: 'Paris', postalCode: '75011' },
  paris18: { city: 'Paris', postalCode: '75018' },
  boulogne: { city: 'Boulogne-Billancourt', postalCode: '92100' },
  montreuil: { city: 'Montreuil', postalCode: '93100' },
  versailles: { city: 'Versailles', postalCode: '78000' },
  lyon3: { city: 'Lyon', postalCode: '69003' },
  lyon7: { city: 'Lyon', postalCode: '69007' },
  villeurbanne: { city: 'Villeurbanne', postalCode: '69100' },
  marseille: { city: 'Marseille', postalCode: '13008' },
  aix: { city: 'Aix-en-Provence', postalCode: '13100' },
  toulouse: { city: 'Toulouse', postalCode: '31000' },
  bordeaux: { city: 'Bordeaux', postalCode: '33000' },
  nantes: { city: 'Nantes', postalCode: '44000' },
  rennes: { city: 'Rennes', postalCode: '35000' },
  lille: { city: 'Lille', postalCode: '59000' },
  roubaix: { city: 'Roubaix', postalCode: '59100' },
  strasbourg: { city: 'Strasbourg', postalCode: '67000' },
  nancy: { city: 'Nancy', postalCode: '54000' },
  montpellier: { city: 'Montpellier', postalCode: '34000' },
  nice: { city: 'Nice', postalCode: '06000' },
  grenoble: { city: 'Grenoble', postalCode: '38000' },
  dijon: { city: 'Dijon', postalCode: '21000' },
  rouen: { city: 'Rouen', postalCode: '76000' },
  tours: { city: 'Tours', postalCode: '37000' },
  clermont: { city: 'Clermont-Ferrand', postalCode: '63000' },
  angers: { city: 'Angers', postalCode: '49000' },
  reims: { city: 'Reims', postalCode: '51100' },
  lehavre: { city: 'Le Havre', postalCode: '76600' },
  toulon: { city: 'Toulon', postalCode: '83000' },
  brest: { city: 'Brest', postalCode: '29200' },
  // Lieux des locations de vacances et des trajets (annonces localisées ailleurs que chez le vendeur)
  sables: { city: "Les Sables-d'Olonne", postalCode: '85100' },
  sarlat: { city: 'Sarlat-la-Canéda', postalCode: '24200' },
  deuxalpes: { city: 'Les Deux Alpes', postalCode: '38860' },
  mimizan: { city: 'Mimizan', postalCode: '40200' },
  vannes: { city: 'Vannes', postalCode: '56000' },
  uzes: { city: 'Uzès', postalCode: '30700' },
  annecy: { city: 'Annecy', postalCode: '74000' },
  colmar: { city: 'Colmar', postalCode: '68000' },
  gordes: { city: 'Gordes', postalCode: '84220' },
  biarritz: { city: 'Biarritz', postalCode: '64200' },
};

const A = (n, firstName, lastName, username, city) => ({ key: username, firstName, lastName, username, phone: '063998' + String(n).padStart(4, '0'), city });
const ACCOUNTS = [
  A(11, 'Inès', 'Lambert', 'ines_lambert', 'paris11'),
  A(12, 'Rayan', 'Meziane', 'rayan_meziane', 'montreuil'),
  A(13, 'Chloé', 'Perrin', 'chloe_perrin', 'boulogne'),
  A(14, 'Amine', 'Bouhaddou', 'amine_bouhaddou', 'paris18'),
  A(15, 'Manon', 'Girard', 'manon_girard', 'versailles'),
  A(16, 'Youssef', 'Khalil', 'youssef_khalil', 'lyon3'),
  A(17, 'Élodie', 'Faure', 'elodie_faure', 'lyon7'),
  A(18, 'Bilal', 'Saïdi', 'bilal_saidi', 'villeurbanne'),
  A(19, 'Pauline', 'Renard', 'pauline_renard', 'marseille'),
  A(20, 'Sofiane', 'Amrani', 'sofiane_amrani', 'marseille'),
  A(21, 'Margaux', 'Dupont', 'margaux_dupont', 'aix'),
  A(22, 'Leïla', 'Benkirane', 'leila_benkirane', 'toulouse'),
  A(23, 'Hugo', 'Lemoine', 'hugo_lemoine', 'toulouse'),
  A(24, 'Salma', 'Ouali', 'salma_ouali', 'bordeaux'),
  A(25, 'Mathieu', 'Chevalier', 'mathieu_chevalier', 'bordeaux'),
  A(26, 'Ilyes', 'Rahmani', 'ilyes_rahmani', 'nantes'),
  A(27, 'Camille', 'Bonnet', 'camille_bonnet', 'nantes'),
  A(28, 'Nour', 'El Amrani', 'nour_elamrani', 'rennes'),
  A(29, 'Maxime', 'Rousseau', 'maxime_rousseau', 'rennes'),
  A(30, 'Aïcha', 'Diallo', 'aicha_diallo', 'lille'),
  A(31, 'Lucas', 'Fontaine', 'lucas_fontaine', 'lille'),
  A(32, 'Omar', 'Tahiri', 'omar_tahiri', 'roubaix'),
  A(33, 'Anaïs', 'Schmitt', 'anais_schmitt', 'strasbourg'),
  A(34, 'Walid', 'Bensaïd', 'walid_bensaid', 'strasbourg'),
  A(35, 'Clara', 'Muller', 'clara_muller', 'nancy'),
  A(36, 'Yanis', 'Belhadj', 'yanis_belhadj', 'montpellier'),
  A(37, 'Juliette', 'Marchand', 'juliette_marchand', 'montpellier'),
  A(38, 'Hamza', 'Zerrouki', 'hamza_zerrouki', 'nice'),
  A(39, 'Océane', 'Blanc', 'oceane_blanc', 'nice'),
  A(40, 'Adam', 'Mansouri', 'adam_mansouri', 'grenoble'),
  A(41, 'Sarah', 'Legrand', 'sarah_legrand', 'grenoble'),
  A(42, 'Nadir', 'Boukhalfa', 'nadir_boukhalfa', 'dijon'),
  A(43, 'Émilie', 'Carpentier', 'emilie_carpentier', 'rouen'),
  A(44, 'Kenza', 'Alaoui', 'kenza_alaoui', 'tours'),
  A(45, 'Julien', 'Masson', 'julien_masson', 'tours'),
  A(46, 'Samir', 'Hadj', 'samir_hadj', 'clermont'),
  A(47, 'Louise', 'Gauthier', 'louise_gauthier', 'angers'),
  A(48, 'Zakaria', 'Ferhat', 'zakaria_ferhat', 'reims'),
  A(49, 'Mélanie', 'Robin', 'melanie_robin', 'lehavre'),
  A(50, 'Idris', 'Chaoui', 'idris_chaoui', 'toulon'),
  A(51, 'Gaëlle', 'Le Gall', 'gaelle_legall', 'brest'),
  A(52, 'Anis', 'Djebbar', 'anis_djebbar', 'lyon3'),
  A(53, 'Charlotte', 'Vidal', 'charlotte_vidal', 'paris11'),
  A(54, 'Ryad', 'Bouzid', 'ryad_bouzid', 'marseille'),
  A(55, 'Alice', 'Petit', 'alice_petit', 'nantes'),
  A(56, 'Farah', 'Nasri', 'farah_nasri', 'lille'),
  A(57, 'Théo', 'Barbier', 'theo_barbier', 'bordeaux'),
  A(58, 'Malik', 'Aouad', 'malik_aouad', 'toulouse'),
  A(59, 'Noémie', 'Collet', 'noemie_collet', 'strasbourg'),
  A(60, 'Ismaël', 'Kaci', 'ismael_kaci', 'montpellier'),
];

module.exports = { CITIES, ACCOUNTS };
