// Archétypes d'annonces (AUDIT §71) — maison & jardin, électronique, loisirs.
const V = (slug, n, def) => ({ slug, n, ...def });
const BON = ['bon_etat', 'tres_bon_etat'];

module.exports = [
  // ---------------------------------------------------------------- Maison & Jardin (100)
  V('ameublement', 6, {
    title: 'Canapé {places} places {matiere} {couleur}',
    desc: 'Canapé {places} places en {matiere} {couleur}, {marque}, {dim}. Confortable et en {etat}, assises non affaissées, non fumeur, sans animaux. {detail} À venir chercher, {acces}.',
    price: [180, 950], cond: BON,
    attrs: { piece: 'Salon', type_meuble: 'Canapé / Fauteuil', matiere: '{matiere}', couleur: '{Couleur}', marque: '{marque}' },
    opts: { places: ['2', '3', '3', 'd\'angle 5'], matiere: ['velours', 'tissu', 'cuir', 'lin'], couleur: ['vert', 'gris', 'bleu', 'beige', 'jaune'], marque: ['Ikea', 'Maisons du Monde', 'La Redoute Intérieurs', 'Bobochic', 'Poltronesofà'], dim: ['200 × 90 cm', '180 × 85 cm', '230 × 95 cm', '260 × 160 cm'], etat: ['très bon état', 'bon état', 'excellent état'], detail: ['Pieds en bois, coussins déhoussables.', 'Convertible avec matelas 140.', 'Coussins déhoussables lavables.', 'Méridienne côté gauche.'], acces: ['rez-de-chaussée', '3e étage avec ascenseur', '2e étage sans ascenseur (prévoir deux personnes)'] },
    q: ['velvet sofa living room', 'modern sofa apartment', 'corner sofa grey'], photos: [2, 4],
  }),
  V('ameublement', 5, {
    title: 'Table à manger {matiere} {dim} + {nb} chaises',
    desc: 'Table à manger en {matiere}, {dim} cm, {forme}, avec {nb} chaises assorties. {detail} Quelques traces d\'usage sur le plateau, structure impeccable. Se démonte pour le transport.',
    price: [150, 690], cond: BON,
    attrs: { piece: 'Cuisine', type_meuble: 'Table', matiere: '{matiere}', couleur: '{Couleur}', marque: '{marque}' },
    opts: { matiere: ['chêne massif', 'bois et métal', 'noyer', 'pin', 'verre et acier'], dim: ['160 × 90', '180 × 90', '140 × 80', '200 × 100'], forme: ['rectangulaire', 'avec rallonge', 'ovale', 'à pieds épingle'], nb: [4, 6, 6, 8], detail: ['Chaises en tissu gris.', 'Chaises en bois courbé.', 'Rallonge de 50 cm incluse.', 'Chaises scandinaves blanches.'], couleur: ['marron', 'beige', 'noir', 'blanc'], marque: ['Ikea', 'Maisons du Monde', 'Habitat', 'Alinéa', 'Artisan local'] },
    q: ['dining table chairs wood', 'oak dining table'], photos: [2, 4],
  }),
  V('ameublement', 5, {
    title: 'Lit {dim} {marque} avec sommier et matelas',
    desc: 'Lit {dim} cm {marque}, {style}, avec sommier à lattes et matelas {matelas} ({age}). Tête de lit {tete}. Démonté et propre, housse de matelas lavée. Transport à prévoir (utilitaire).',
    price: [150, 750], cond: BON,
    attrs: { piece: 'Chambre', type_meuble: 'Lit / Literie', matiere: '{matiere}', couleur: '{Couleur}', marque: '{marque}' },
    opts: { dim: ['140 × 190', '160 × 200', '140 × 200', '180 × 200'], marque: ['Ikea', 'Maisons du Monde', 'Tediber', 'Emma', 'Conforama'], style: ['cadre en bois', 'coffre de rangement', 'style scandinave', 'cadre en métal'], matelas: ['Emma Original', 'Tediber', 'Ikea Vesteröy', 'Bultex'], age: ['2 ans', '18 mois', '3 ans', '1 an'], tete: ['capitonnée en tissu', 'en bois', 'en cannage', 'en métal'], matiere: ['bois', 'bois', 'tissu', 'métal'], couleur: ['gris', 'blanc', 'beige', 'noir'] },
    pair: { style: 'matiere' },
    q: ['bedroom bed frame mattress', 'scandinavian bedroom'], photos: [2, 4],
  }),
  V('ameublement', 5, {
    title: 'Armoire {dim} {matiere} {couleur}',
    desc: 'Armoire {marque} {dim}, {portes}, en {matiere} {couleur}, {agencement}. Portes bien alignées, aucune casse. À démonter sur place, notice disponible. Prévoir deux personnes.',
    price: [80, 420], cond: BON,
    attrs: { piece: 'Chambre', type_meuble: 'Armoire / Rangement', matiere: '{matiere}', couleur: '{Couleur}', marque: '{marque}' },
    opts: { marque: ['Ikea Pax', 'Ikea Brimnes', 'Conforama', 'Maisons du Monde'], dim: ['200 × 200 cm', '150 × 200 cm', '100 × 190 cm', '250 × 236 cm'], portes: ['portes coulissantes', '2 portes battantes', '3 portes', 'portes miroir'], matiere: ['bois mélaminé', 'pin massif', 'chêne', 'bois'], couleur: ['blanc', 'gris', 'marron', 'noir'], agencement: ['penderie double, étagères et tiroirs', 'penderie et étagères', 'tiroirs intérieurs'] },
    q: ['wardrobe bedroom white', 'wooden wardrobe closet'], photos: [2, 3],
  }),
  V('ameublement', 5, {
    title: 'Bureau {style} {dim} {couleur}',
    desc: 'Bureau {style} {dim} cm, {couleur}, {detail}. Utilisé pour le télétravail, plateau sans rayure. {chaise}',
    price: [40, 390], cond: BON,
    attrs: { piece: 'Bureau', type_meuble: 'Bureau', matiere: '{matiere}', couleur: '{Couleur}', marque: '{marque}' },
    opts: { style: ['assis-debout électrique', 'en chêne', 'd\'angle', 'scandinave', 'en métal et bois'], dim: ['140 × 70', '120 × 60', '160 × 80', '110 × 55'], couleur: ['blanc', 'marron', 'noir', 'beige'], detail: ['moteur silencieux, mémoire de deux positions', 'deux tiroirs, passe-câbles', 'grand retour à gauche', 'pieds compas, tiroir central', 'pieds épingle noirs'], matiere: ['bois et acier', 'chêne', 'mélaminé', 'bois', 'bois et métal'], marque: ['Flexispot', 'Ikea', 'Alinéa', 'Maisons du Monde', 'Tiptoe'], chaise: ['Chaise de bureau vendue à part.', 'Chaise ergonomique offerte.', 'Sans chaise.'] },
    pair: { style: 'detail', style2: 'matiere', style3: 'marque' },
    q: ['standing desk home office', 'wooden desk office', 'home office desk'], photos: [2, 3],
  }),
  V('ameublement', 5, {
    title: '{meuble} {matiere} {couleur}',
    desc: '{meuble} en {matiere} {couleur}, {dim}, {detail}. Bon état général, {defaut}. À venir chercher.',
    price: [25, 320], cond: BON,
    attrs: { piece: '{piece}', type_meuble: '{typeAttr}', matiere: '{matiere}', couleur: '{Couleur}', marque: '{marque}' },
    opts: { meuble: ['Bibliothèque', 'Meuble TV', 'Buffet', 'Étagère murale (lot de 3)', 'Fauteuil'], typeAttr: ['Étagère', 'Meuble TV', 'Armoire / Rangement', 'Étagère', 'Canapé / Fauteuil'], piece: ['Salon', 'Salon', 'Cuisine', 'Salon', 'Salon'], matiere: ['bois', 'chêne', 'teck', 'bois', 'velours'], couleur: ['blanc', 'marron', 'marron', 'noir', 'vert'], dim: ['200 × 80 cm', '180 × 45 cm', '160 × 90 cm', '80 × 20 cm', 'assise 45 cm'], detail: ['cinq étagères réglables', 'deux niches et un tiroir', 'trois portes et deux tiroirs', 'fixations murales fournies', 'pieds en hêtre'], defaut: ['une légère marque sur le côté', 'aucun défaut', 'patine du bois', 'aucun défaut', 'un coussin légèrement affaissé'], marque: ['Ikea', 'Maisons du Monde', 'Vintage', 'Ikea', 'La Redoute'] },
    pair: { meuble: 'typeAttr', meuble2: 'piece', meuble3: 'matiere', meuble4: 'couleur', meuble5: 'dim', meuble6: 'detail', meuble7: 'defaut', meuble8: 'marque' },
    q: ['bookshelf living room', 'tv stand wood', 'sideboard teak', 'wall shelves', 'velvet armchair'], qByOpt: 'meuble', photos: [2, 3],
  }),
  V('ameublement', 4, {
    title: 'Salon de jardin {matiere} {places} places',
    desc: 'Salon de jardin en {matiere}, {places} places, {composition}. Coussins {coussins}, structure sans rouille ni casse. Rangé sous abri chaque hiver. Vendu avec sa housse de protection.',
    price: [120, 690], cond: BON,
    attrs: { piece: 'Extérieur', type_meuble: 'Canapé / Fauteuil', matiere: '{matiere}', couleur: '{Couleur}', marque: '{marque}' },
    opts: { matiere: ['résine tressée', 'aluminium', 'acacia', 'teck'], places: [4, 5, 6], composition: ['canapé 2 places, 2 fauteuils, table basse', 'table 180 cm et 6 chaises', 'canapé d\'angle et table', '2 fauteuils, table basse'], coussins: ['déhoussables, lavés', 'neufs de cette année', 'un peu décolorés'], couleur: ['gris', 'noir', 'marron', 'beige'], marque: ['Hespéride', 'Leroy Merlin', 'Maisons du Monde', 'Castorama'] },
    q: ['garden furniture set patio', 'outdoor lounge set'], photos: [2, 4],
  }),
  V('electromenager', 5, {
    title: 'Lave-linge {marque} {kg} kg {classe}',
    desc: 'Lave-linge {marque} {modele} {kg} kg, {tours} tours/min, classe {classe}, acheté {achat}. Fonctionne parfaitement, {detail}. Vendu pour cause de déménagement. Prévoir deux personnes pour le transport.',
    price: [120, 420], cond: BON,
    attrs: { type_appareil: 'Lave-linge', marque: '{marque}', classe_energie: '{classe}' },
    opts: { marque: ['Bosch', 'Samsung', 'LG', 'Whirlpool', 'Miele'], modele: ['Série 4', 'EcoBubble', 'AI DD', 'FreshCare', 'W1'], kg: [7, 8, 9], tours: [1200, 1400], classe: ['A', 'B', 'C'], achat: ['en 2022', 'en 2023', 'il y a 3 ans'], detail: ['joint et filtre nettoyés', 'facture et garantie restante', 'silencieux, moteur inverter'] },
    pair: { marque: 'modele' },
    q: ['washing machine laundry', 'front load washer'], photos: [2, 3],
  }),
  V('electromenager', 4, {
    title: 'Réfrigérateur {type} {marque} {litres} L',
    desc: 'Réfrigérateur {type} {marque}, {litres} litres, {detail}, classe {classe}. Froid ventilé, aucun bruit anormal, joints parfaits. Dégivré et nettoyé, prêt à partir.',
    price: [150, 690], cond: BON,
    attrs: { type_appareil: 'Réfrigérateur / Congélateur', marque: '{marque}', classe_energie: '{classe}' },
    opts: { type: ['combiné', 'américain', 'une porte', 'combiné'], marque: ['Samsung', 'LG', 'Beko', 'Liebherr', 'Haier'], litres: [300, 450, 240, 340], detail: ['congélateur en bas 3 tiroirs', 'distributeur d\'eau et de glaçons', 'freezer intégré', 'inox anti-traces'], classe: ['A', 'B', 'C', 'D'] },
    pair: { type: 'litres', type2: 'detail' },
    q: ['refrigerator kitchen stainless', 'fridge freezer'], photos: [2, 3],
  }),
  V('electromenager', 4, {
    title: 'Lave-vaisselle {marque} {couverts} couverts',
    desc: 'Lave-vaisselle {marque} {couverts} couverts, {pose}, {db} dB, classe {classe}. Acheté {achat}, révisé, tuyaux fournis. {detail}',
    price: [120, 390], cond: BON,
    attrs: { type_appareil: 'Lave-vaisselle', marque: '{marque}', classe_energie: '{classe}' },
    opts: { marque: ['Bosch', 'Siemens', 'Whirlpool', 'Electrolux', 'Candy'], couverts: [12, 13, 14], pose: ['pose libre', 'encastrable', 'pose libre'], db: [44, 46, 48], classe: ['C', 'D', 'E'], achat: ['en 2021', 'en 2022', 'en 2023'], detail: ['Troisième tiroir à couverts.', 'Programme rapide 30 min.', 'Départ différé, séchage parfait.'] },
    q: ['dishwasher kitchen open', 'dishwasher appliance'], photos: [2, 3],
  }),
  V('electromenager', 7, {
    title: '{appareil} {marque} {modele}',
    desc: '{appareil} {marque} {modele}, {detail}. Utilisé {usage}, fonctionne parfaitement, accessoires et notice fournis. {etat}',
    price: [25, 390], cond: BON,
    attrs: { type_appareil: '{typeAttr}', marque: '{marque}' },
    opts: { appareil: ['Aspirateur balai', 'Robot cuiseur', 'Machine à café à grains', 'Micro-ondes', 'Four encastrable', 'Sèche-linge', 'Friteuse sans huile'], typeAttr: ['Aspirateur', 'Petit électroménager', 'Petit électroménager', 'Micro-ondes', 'Four / Cuisinière', 'Sèche-linge', 'Petit électroménager'], marque: ['Dyson', 'Thermomix', 'De\'Longhi', 'Samsung', 'Bosch', 'Bosch', 'Ninja'], modele: ['V11', 'TM6', 'Magnifica S', '23 L grill', 'Série 6 pyrolyse', '8 kg pompe à chaleur', 'Dual Zone'], detail: ['autonomie 60 min, batterie récente', 'avec Cookidoo actif jusqu\'en 2027', 'broyeur réglable, buse vapeur', '800 W, plateau tournant', 'chaleur tournante, porte froide', 'classe A++, condensation', 'deux paniers indépendants'], usage: ['un an', 'deux ans', '18 mois', 'trois ans'], etat: ['Comme neuf.', 'Très bon état.', 'Traces d\'usage minimes.'] },
    pair: { appareil: 'typeAttr', appareil2: 'marque', appareil3: 'modele', appareil4: 'detail' },
    q: ['cordless stick vacuum', 'thermomix kitchen', 'espresso machine beans', 'microwave oven', 'built-in oven kitchen', 'tumble dryer', 'air fryer'], qByOpt: 'appareil', photos: [2, 3],
  }),
  V('decoration', 8, {
    title: '{objet} {style}',
    desc: '{objet} {style}, {dim}, {detail}. {origine} Bon état, {defaut}.',
    price: [15, 260], cond: BON,
    attrs: { marque: '{marque}', couleur: '{couleur}' },
    opts: { objet: ['Miroir', 'Tapis', 'Lampe à poser', 'Suspension', 'Lot de cadres', 'Vase en céramique', 'Horloge murale', 'Plaid en laine'], style: ['doré ancien', 'berbère en laine', 'en laiton et opaline', 'en rotin', 'noirs (lot de 6)', 'artisanal', 'vintage', 'tissé main'], dim: ['80 × 60 cm', '200 × 140 cm', '45 cm de haut', '50 cm de diamètre', 'formats 20 × 30 à 40 × 50', '35 cm', '40 cm', '130 × 170 cm'], detail: ['cadre en bois sculpté', 'motifs losanges, franges', 'douille E27, câble tissu', 'avec ampoule', 'passe-partout inclus', 'émail bleu', 'mécanisme silencieux', 'couleurs naturelles'], origine: ['Chiné en brocante.', 'Acheté au Maroc.', 'Acheté chez un artisan.', 'Maisons du Monde.', 'Ikea.', 'Fait main par une potière locale.', 'Vintage années 70.', 'Rapporté d\'Écosse.'], defaut: ['une petite tache sur le cadre', 'aucune usure', 'câble à changer si souhaité', 'aucun défaut', 'un verre à remplacer', 'aucun défaut', 'pile à changer', 'aucune tache'], marque: ['Sans marque', 'Artisanal', 'Maisons du Monde', 'Ikea', 'Ikea', 'Artisanal', 'Vintage', 'Artisanal'], couleur: ['doré', 'beige', 'blanc', 'naturel', 'noir', 'bleu', 'marron', 'écru'] },
    pair: { objet: 'style', objet2: 'dim', objet3: 'detail', objet4: 'origine', objet5: 'defaut', objet6: 'marque', objet7: 'couleur' },
    q: ['antique gold mirror', 'berber wool rug', 'brass table lamp', 'rattan pendant lamp', 'black picture frames', 'ceramic vase', 'vintage wall clock', 'wool blanket plaid'], qByOpt: 'objet', photos: [2, 3],
  }),
  V('decoration', 7, {
    title: '{objet}, {detail}',
    desc: '{objet}, {detail}. {origine} {etat} Remise en main propre, emballage soigné.',
    price: [10, 180], cond: BON,
    attrs: { marque: '{marque}', couleur: '{couleur}' },
    opts: { objet: ['Service de table 24 pièces', 'Lot de 6 verres à vin', 'Plantes d\'intérieur (lot de 4)', 'Rideaux occultants', 'Coussins (lot de 4)', 'Bougeoirs en laiton', 'Théière en fonte'], detail: ['porcelaine blanche, sans ébréchure', 'cristal soufflé, hauteur 22 cm', 'monstera, pothos, ficus et pilea, en pot', '2 panneaux 140 × 260 cm, gris', 'housses en lin lavé, 45 × 45', 'lot de trois, hauteurs différentes', '0,8 L, avec filtre'], origine: ['Cadeau de mariage jamais utilisé.', 'Achetés chez un verrier.', 'Bouturées par mes soins.', 'Achetés l\'an dernier.', 'La Redoute Intérieurs.', 'Chinés en brocante.', 'Rapportée du Japon.'], etat: ['Complet.', 'Aucune trace.', 'En pleine forme.', 'Œillets impeccables.', 'Lavées.', 'Patine naturelle.', 'Sans fuite.'], marque: ['Villeroy & Boch', 'Sans marque', 'Sans marque', 'Madura', 'La Redoute', 'Vintage', 'Sans marque'], couleur: ['blanc', 'transparent', 'vert', 'gris', 'beige', 'doré', 'noir'] },
    pair: { objet: 'detail', objet2: 'origine', objet3: 'etat', objet4: 'marque', objet5: 'couleur' },
    q: ['white porcelain dinner set', 'wine glasses crystal', 'houseplants pots', 'blackout curtains', 'linen cushions sofa', 'brass candle holders', 'cast iron teapot'], qByOpt: 'objet', photos: [2, 3],
  }),
  V('bricolage', 8, {
    title: '{outil} {marque} {detail}',
    desc: '{outil} {marque}, {detail}, {etat}. {usage} Vendu avec {inclus}. Test possible sur place.',
    price: [30, 420], cond: BON,
    attrs: { type_outil: '{typeAttr}', marque: '{marque}' },
    opts: { outil: ['Perceuse-visseuse', 'Scie circulaire', 'Ponceuse excentrique', 'Meuleuse d\'angle', 'Scie sauteuse', 'Perforateur', 'Compresseur 50 L', 'Établi pliant'], typeAttr: ['Outillage électroportatif', 'Outillage électroportatif', 'Outillage électroportatif', 'Outillage électroportatif', 'Outillage électroportatif', 'Outillage électroportatif', 'Outillage électroportatif', 'Outillage à main'], marque: ['Makita', 'Bosch', 'Festool', 'DeWalt', 'Bosch', 'Hilti', 'Michelin', 'Wolfcraft'], detail: ['18 V, 2 batteries 5 Ah', '1 400 W lame 190 mm', '150 mm avec aspiration', '125 mm 900 W', 'pendulaire 650 W', 'SDS-Plus 3 kg', '2 CV bicylindre', '600 kg de charge'], etat: ['très bon état', 'bon état', 'peu servi', 'état correct'], usage: ['Utilisée pour une rénovation.', 'Sert depuis deux ans en bricolage du week-end.', 'Achetée pour un seul chantier.', 'Matériel d\'artisan retraité.'], inclus: ['coffret et chargeur', 'sa mallette', 'disques abrasifs', 'trois disques', 'jeu de lames', 'forets et burins', 'tuyau et soufflette', 'ses serre-joints'] },
    pair: { outil: 'typeAttr', outil2: 'marque', outil3: 'detail', outil4: 'inclus' },
    q: ['cordless drill', 'circular saw', 'orbital sander', 'angle grinder', 'jigsaw tool', 'rotary hammer drill', 'air compressor', 'folding workbench'], qByOpt: 'outil', photos: [2, 3],
  }),
  V('bricolage', 7, {
    title: '{lot}, {etat}',
    desc: '{lot} : {detail}. Reste de chantier, {etat}. Prix pour l\'ensemble, à venir chercher (prévoir un utilitaire selon la quantité).',
    price: [20, 350], cond: BON,
    attrs: { type_outil: '{typeAttr}', marque: '{marque}' },
    opts: { lot: ['Carrelage grès cérame 60 × 60', 'Parquet stratifié chêne', 'Lot de peinture', 'Radiateurs en fonte', 'Robinetterie et vasque', 'Caisse à outils complète', 'Échelle télescopique 3,80 m'], typeAttr: ['Matériaux', 'Matériaux', 'Matériaux', 'Plomberie / Électricité', 'Plomberie / Électricité', 'Outillage à main', 'Outillage à main'], detail: ['18 m², gris, 12 cartons neufs', '22 m² restants, classe 32', '4 pots de 10 L blanc mat et velours', 'deux radiateurs 10 éléments, sablés', 'mitigeur Grohe et vasque à poser', 'clés, pinces, tournevis, niveau, mètre', 'aluminium, charge 150 kg'], etat: ['neuf', 'neuf jamais posé', 'entamé', 'à repeindre', 'neuf', 'complète', 'peu servie'], marque: ['Leroy Merlin', 'Quick-Step', 'Tollens', 'Vintage', 'Grohe', 'Facom', 'Hailo'] },
    pair: { lot: 'typeAttr', lot2: 'detail', lot3: 'etat', lot4: 'marque' },
    q: ['floor tiles boxes', 'laminate flooring planks', 'paint cans', 'cast iron radiator', 'bathroom faucet sink', 'toolbox tools', 'telescopic ladder'], qByOpt: 'lot', photos: [2, 3],
  }),
  V('jardinage', 8, {
    title: '{outil} {marque} {detail}',
    desc: '{outil} {marque}, {detail}, {etat}. {entretien} {inclus}',
    price: [40, 650], cond: BON,
    attrs: { type_jardin: '{typeAttr}' },
    opts: { outil: ['Tondeuse thermique', 'Tondeuse robot', 'Taille-haie électrique', 'Souffleur à batterie', 'Motobineuse', 'Nettoyeur haute pression', 'Tronçonneuse', 'Broyeur de végétaux'], typeAttr: ['Tondeuse', 'Tondeuse', 'Outillage de jardin', 'Outillage de jardin', 'Outillage de jardin', 'Outillage de jardin', 'Outillage de jardin', 'Outillage de jardin'], marque: ['Honda', 'Gardena', 'Bosch', 'Stihl', 'Einhell', 'Kärcher', 'Husqvarna', 'Bosch'], detail: ['46 cm tractée, bac 55 L', 'Sileno 500 m², station et câble', '60 cm, 550 W', 'BGA 57 avec batterie', '140 cm³, 4 fraises', 'K5, 145 bars', '40 cm guide, 2 CV', 'AXT 25 TC, 2 500 W'], etat: ['révisée au printemps', 'un an de service', 'très bon état', 'comme neuf', 'bon état', 'très bon état', 'chaîne neuve', 'peu servi'], entretien: ['Vidange faite, démarre au quart de tour.', 'Lames neuves.', 'Lame affûtée.', 'Batterie à 100 % de capacité.', 'Fraises affûtées.', 'Joints vérifiés.', 'Carburateur nettoyé.', 'Lames retournées.'], inclus: ['Vendue avec bidon et huile.', 'Vendue avec 200 m de câble supplémentaire.', 'Rallonge de 20 m incluse.', 'Chargeur inclus.', 'Notice fournie.', 'Brosse terrasse incluse.', 'Housse et lime incluses.', 'Sac de ramassage inclus.'] },
    pair: { outil: 'typeAttr', outil2: 'marque', outil3: 'detail', outil4: 'etat', outil5: 'entretien', outil6: 'inclus' },
    q: ['lawn mower grass', 'robot lawn mower', 'hedge trimmer', 'leaf blower', 'garden tiller', 'pressure washer', 'chainsaw', 'garden shredder'], qByOpt: 'outil', photos: [2, 3],
  }),
  V('jardinage', 7, {
    title: '{article} {detail}',
    desc: '{article}, {detail}. {etat} {origine} À venir chercher.',
    price: [20, 590], cond: BON,
    attrs: { type_jardin: '{typeAttr}' },
    opts: { article: ['Barbecue Weber', 'Plancha gaz', 'Olivier en pot', 'Serre de jardin', 'Table de jardin extensible', 'Composteur', 'Piscine hors-sol'], typeAttr: ['Barbecue / Plancha', 'Barbecue / Plancha', 'Plantes', 'Mobilier de jardin', 'Mobilier de jardin', 'Autre', 'Piscine'], detail: ['Spirit E-310 3 brûleurs, housse', 'Forge Adour 2 brûleurs sur chariot', 'tronc de 12 cm, 1,80 m de haut, pot en terre cuite', 'polycarbonate 6 m², rayonnages', 'aluminium 160-240 cm, 8 personnes', 'bois 800 L, deux compartiments', 'tubulaire 4,50 × 2,20 m, pompe à sable'], etat: ['Grilles neuves de cette saison.', 'Plaque impeccable.', 'Taillé chaque année, jamais gelé.', 'Démontée, toutes les pièces numérotées.', 'Aucune rayure.', 'Solide, à repeindre.', 'Liner sans fuite, bâche incluse.'], origine: ['Achetée en 2022.', 'Achetée en 2023.', 'Acheté à Nîmes.', 'Montée deux saisons.', 'Achetée chez Leroy Merlin.', 'Fabrication maison.', 'Utilisée deux étés.'] },
    pair: { article: 'typeAttr', article2: 'detail', article3: 'etat', article4: 'origine' },
    q: ['gas barbecue grill garden', 'plancha grill outdoor', 'olive tree pot terrace', 'greenhouse garden', 'garden dining table aluminium', 'wooden compost bin', 'above ground pool garden'], qByOpt: 'article', photos: [2, 3],
  }),

  // ---------------------------------------------------------------- Électronique (70)
  V('telephonie', 8, {
    title: 'iPhone {modele} {stockage} {couleur}',
    desc: 'iPhone {modele} {stockage}, {couleur}, débloqué tout opérateur, batterie à {batterie} % de capacité. {etat} Vendu avec câble{boite}. Facture disponible, remise en main propre pour vérifier ensemble.',
    price: [280, 890], cond: ['tres_bon_etat', 'bon_etat'],
    attrs: { type_produit: 'Smartphone', marque: 'Apple', modele: 'iPhone {modele}', stockage: '{stockage}', couleur: '{couleur}', debloque: true },
    opts: { modele: ['12', '13', '13 mini', '14', '14 Pro', '15', '11', 'SE 2022'], stockage: ['64 Go', '128 Go', '128 Go', '256 Go'], couleur: ['noir', 'blanc', 'bleu', 'vert', 'violet', 'rouge'], batterie: [86, 89, 92, 95, 98], etat: ['Aucune rayure, toujours protégé par une coque et un verre trempé.', 'Micro-rayures sur les tranches, écran parfait.', 'État impeccable.'], boite: [' et boîte d\'origine', '', ' et coque'] },
    q: ['iPhone smartphone black', 'iphone on table'], photos: [2, 4],
  }),
  V('telephonie', 6, {
    title: 'Samsung Galaxy {modele} {stockage}',
    desc: 'Samsung Galaxy {modele} {stockage}, {couleur}, débloqué, {etat}. Batterie en bonne santé, Android à jour. Vendu avec chargeur{boite}.',
    price: [150, 690], cond: ['tres_bon_etat', 'bon_etat'],
    attrs: { type_produit: 'Smartphone', marque: 'Samsung', modele: 'Galaxy {modele}', stockage: '{stockage}', couleur: '{couleur}', debloque: true },
    opts: { modele: ['S22', 'S23', 'A54', 'S21 FE', 'A34', 'S23 FE'], stockage: ['128 Go', '256 Go'], couleur: ['noir', 'blanc', 'vert', 'violet', 'crème'], etat: ['écran sans rayure', 'très bon état', 'quelques traces sur le dos, écran parfait'], boite: [' et boîte', '', ' et étui'] },
    q: ['samsung galaxy smartphone', 'android phone hand'], photos: [2, 3],
  }),
  V('telephonie', 6, {
    title: '{produit} {marqueTxt} {modele}',
    desc: '{produit} {marqueTxt} {modele}, {detail}, {etat}. {inclus} Facture disponible.',
    price: [60, 420], cond: ['tres_bon_etat', 'bon_etat'],
    attrs: { type_produit: '{typeAttr}', marque: '{marque}', modele: '{modele}', couleur: '{couleur}' },
    opts: { produit: ['Montre connectée', 'Montre connectée', 'Smartphone', 'Smartphone', 'Écouteurs', 'Montre connectée'], typeAttr: ['Montre connectée', 'Montre connectée', 'Smartphone', 'Smartphone', 'Accessoire', 'Montre connectée'], marque: ['Apple', 'Samsung', 'Google', 'Xiaomi', 'Apple', 'Autre'], marqueTxt: ['Apple', 'Samsung', 'Google', 'Xiaomi', 'Apple', 'Garmin'], modele: ['Watch Series 8 45 mm', 'Galaxy Watch 6', 'Pixel 7a', 'Redmi Note 12 Pro', 'AirPods Pro 2', 'Forerunner 255'], detail: ['GPS, boîtier aluminium', '44 mm Bluetooth', '128 Go débloqué', '256 Go débloqué', 'boîtier MagSafe', 'GPS multibande'], etat: ['aucune rayure', 'très bon état', 'écran parfait', 'comme neuf', 'embouts neufs', 'bracelet neuf'], inclus: ['Deux bracelets et chargeur inclus.', 'Chargeur inclus.', 'Coque et chargeur inclus.', 'Boîte et chargeur.', 'Boîte d\'origine.', 'Câble de charge inclus.'], couleur: ['noir', 'argent', 'gris', 'bleu', 'blanc', 'noir'] },
    pair: { produit: 'typeAttr', produit2: 'marque', produit3: 'modele', produit4: 'detail', produit5: 'etat', produit6: 'inclus', produit7: 'couleur', produit8: 'marqueTxt' },
    q: ['apple watch wrist', 'samsung galaxy watch', 'google pixel phone', 'xiaomi smartphone', 'airpods pro case', 'garmin running watch'], qByOpt: 'produit', photos: [2, 3],
  }),
  V('informatique', 7, {
    title: 'MacBook {modele} {puce} {ram} / {ssd}',
    desc: 'MacBook {modele} {puce}, {ram} de RAM, SSD {ssd}, {annee}. {cycles} cycles de batterie, clavier AZERTY, aucun choc. Réinitialisé, chargeur d\'origine{boite}. Facture Apple disponible.',
    price: [650, 1690], cond: ['tres_bon_etat', 'bon_etat'],
    attrs: { type_produit: 'Ordinateur portable', marque: 'Apple', processeur: 'Apple {puce}', ram: '{ram}', stockage: '{ssd} SSD', taille_ecran: '{ecran}' },
    opts: { modele: ['Air 13"', 'Pro 14"', 'Air 13"', 'Air 15"', 'Pro 13"'], puce: ['M1', 'M2', 'M2', 'M3', 'M1'], ram: ['8 Go', '16 Go', '16 Go'], ssd: ['256 Go', '512 Go', '512 Go', '1 To'], ecran: [13, 14, 13, 15, 13], annee: ['de 2021', 'de 2023', 'de 2022', 'de 2024', 'de 2020'], cycles: [40, 85, 120, 160, 210], boite: [' et boîte', '', ' et housse'] },
    pair: { modele: 'ecran', modele2: 'annee' },
    q: ['macbook air laptop desk', 'macbook pro laptop'], photos: [2, 4],
  }),
  V('informatique', 6, {
    title: 'PC portable {marque} {modele} {ecran}" {proc}',
    desc: 'PC portable {marque} {modele}, écran {ecran}" {dalle}, {proc}, {ram} de RAM, SSD {ssd}. {usage} Windows 11 réinstallé proprement, batterie {batterie}. Chargeur inclus.',
    price: [280, 1290], cond: BON,
    attrs: { type_produit: 'Ordinateur portable', marque: '{marque}', processeur: '{proc}', ram: '{ram}', stockage: '{ssd} SSD', taille_ecran: '{ecran}' },
    opts: { marque: ['Lenovo', 'Dell', 'HP', 'Asus', 'Acer', 'MSI'], modele: ['ThinkPad T14', 'XPS 13', 'Pavilion 15', 'Zenbook 14', 'Aspire 5', 'Katana 15'], ecran: [14, 13, 15, 14, 15, 15], dalle: ['IPS mat', 'OLED', 'Full HD', 'OLED', 'Full HD', '144 Hz'], proc: ['Intel Core i5 11e gén.', 'Intel Core i7 12e gén.', 'AMD Ryzen 5', 'Intel Core i7 13e gén.', 'AMD Ryzen 7', 'Intel Core i7 + RTX 4060'], ram: ['16 Go', '16 Go', '8 Go', '16 Go', '16 Go', '32 Go'], ssd: ['512 Go', '512 Go', '256 Go', '1 To', '512 Go', '1 To'], usage: ['Utilisé pour le télétravail.', 'Machine de bureau, aucune rayure.', 'Ordinateur familial.', 'Acheté pour les études.', 'Usage bureautique.', 'PC gaming, jamais overclocké.'], batterie: ['tient 6 h', 'en bonne santé', 'tient 4 h', 'excellente', 'correcte', 'tient 3 h'] },
    pair: { marque: 'modele', marque2: 'ecran', marque3: 'dalle', marque4: 'proc', marque5: 'ram', marque6: 'ssd', marque7: 'usage' },
    q: ['lenovo thinkpad laptop', 'dell xps laptop', 'hp laptop desk', 'asus zenbook', 'acer laptop', 'gaming laptop rgb'], qByOpt: 'marque', photos: [2, 3],
  }),
  V('informatique', 7, {
    title: '{produit} {marque} {modele}',
    desc: '{produit} {marque} {modele}, {detail}. {etat} {inclus}',
    price: [40, 890], cond: BON,
    attrs: { type_produit: '{typeAttr}', marque: '{marque}', stockage: '{stockage}', taille_ecran: '{ecran}' },
    opts: { produit: ['iPad', 'Écran', 'Imprimante', 'PC fixe', 'Tablette', 'Écran gaming', 'Clavier mécanique'], typeAttr: ['Tablette', 'Écran', 'Imprimante', 'Ordinateur fixe', 'Tablette', 'Écran', 'Périphérique'], marque: ['Apple', 'Dell', 'HP', 'Assemblé', 'Samsung', 'LG', 'Keychron'], modele: ['Air 5 64 Go', 'UltraSharp 27" 4K', 'OfficeJet Pro 9010', 'Ryzen 5 / RTX 3060', 'Galaxy Tab S8', 'UltraGear 27" 165 Hz', 'K2 sans fil'], detail: ['Wi-Fi, puce M1, étui clavier', 'USB-C, pied réglable', 'recto-verso, Wi-Fi, cartouches neuves', '16 Go RAM, SSD 1 To, boîtier Fractal', '128 Go avec S Pen', '1440p, 1 ms', 'switches rouges, rétroéclairé'], etat: ['Aucune rayure.', 'Dalle parfaite, sans pixel mort.', 'Compteur 4 000 pages.', 'Monté en 2023, silencieux.', 'Protection d\'écran posée.', 'Comme neuf.', 'Peu utilisé.'], inclus: ['Chargeur inclus.', 'Câbles fournis.', 'Câble USB fourni.', 'Windows 11 activé.', 'Housse incluse.', 'Câble DisplayPort inclus.', 'Câble USB-C inclus.'], stockage: ['64 Go', '', '', '1 To SSD', '128 Go', '', ''], ecran: [10.9, 27, 5, 5, 11, 27, 5] },
    pair: { produit: 'typeAttr', produit2: 'marque', produit3: 'modele', produit4: 'detail', produit5: 'etat', produit6: 'inclus', produit7: 'stockage', produit8: 'ecran' },
    q: ['ipad tablet desk', 'computer monitor 4k desk', 'office printer', 'gaming pc tower', 'samsung tablet', 'gaming monitor', 'mechanical keyboard'], qByOpt: 'produit', photos: [2, 3],
  }),
  V('consoles-jeux-video', 5, {
    title: 'PlayStation 5 {edition} + {manettes} manette{s}',
    desc: 'PS5 {edition}, achetée {achat}, avec {manettes} manette{s} DualSense et câbles d\'origine. {detail} Fonctionne parfaitement, réinitialisée. Remise en main propre pour tester ensemble.',
    price: [280, 450], cond: BON,
    attrs: { plateforme: 'PlayStation 5', type_produit: 'Console' },
    opts: { edition: ['édition standard', 'Digital Edition', 'Slim', 'édition standard'], manettes: [1, 2, 2], s: ['', 's', 's'], achat: ['en 2022', 'en 2023', 'en 2024'], detail: ['Deux jeux physiques offerts.', 'Station de charge incluse.', 'Boîte d\'origine.'] },
    pair: { manettes: 's' },
    q: ['playstation 5 console controller', 'ps5 console'], photos: [2, 3],
  }),
  V('consoles-jeux-video', 4, {
    title: 'Nintendo Switch {modele} + {jeux} jeux',
    desc: 'Nintendo Switch {modele} avec {jeux} jeux ({liste}), dock, Joy-Con {couleur}, étui de transport. {etat} Console réinitialisée, compte déconnecté.',
    price: [180, 340], cond: BON,
    attrs: { plateforme: 'Nintendo Switch', type_produit: 'Console' },
    opts: { modele: ['OLED', 'standard', 'Lite', 'OLED'], jeux: [2, 3, 4, 5], liste: ['Mario Kart 8, Zelda BOTW', 'Animal Crossing, Mario Odyssey, Pokémon Écarlate', 'Zelda TOTK, Mario Kart 8, Splatoon 3, Kirby', 'Mario Party, Just Dance, Zelda, Mario Kart, Minecraft'], couleur: ['rouge et bleu', 'gris', 'turquoise', 'blancs'], etat: ['Écran sans rayure.', 'Très bon état.', 'Quelques traces sur le dock.'] },
    pair: { jeux: 'liste' },
    q: ['nintendo switch console games', 'nintendo switch oled'], photos: [2, 3],
  }),
  V('consoles-jeux-video', 6, {
    title: 'Lot de {nb} jeux {plateforme}',
    desc: 'Lot de {nb} jeux {plateforme} : {liste}. Boîtiers et disques en très bon état, notices présentes. Vendus en lot uniquement.',
    price: [30, 120], cond: ['tres_bon_etat', 'bon_etat'],
    attrs: { plateforme: '{plateforme}', type_produit: 'Jeu' },
    opts: { nb: [4, 5, 6], plateforme: ['PlayStation 5', 'PlayStation 4', 'Nintendo Switch', 'Xbox Series', 'Xbox One', 'PlayStation 4'], liste: ['God of War Ragnarök, Spider-Man 2, Gran Turismo 7, FC 24', 'The Last of Us 2, Uncharted 4, Horizon, Red Dead 2, GTA V', 'Mario Odyssey, Luigi\'s Mansion 3, Pokémon Violet, Kirby, Mario Party', 'Forza Horizon 5, Halo Infinite, Starfield, FC 24', 'Gears 5, Forza 4, Fallout 4, Sea of Thieves', 'FIFA 21, Assassin\'s Creed Valhalla, Ghost of Tsushima, Spider-Man'] },
    pair: { plateforme: 'liste' },
    q: ['video game cases stack', 'playstation games collection'], photos: [2, 3],
  }),
  V('image-son', 5, {
    title: 'TV {marque} {pouces}" {techno} 4K',
    desc: 'Téléviseur {marque} {pouces} pouces {techno} 4K, {annee}, {smart}. Dalle sans pixel mort ni rayure, télécommande et pied d\'origine. {detail} Transport à prévoir avec une couverture.',
    price: [250, 1100], cond: BON,
    attrs: { type_produit: 'Téléviseur', marque: '{marque}' },
    opts: { marque: ['LG', 'Samsung', 'Sony', 'Philips', 'TCL'], pouces: [55, 65, 50, 48, 75], techno: ['OLED', 'QLED', 'OLED', 'Ambilight', 'QLED'], annee: ['de 2022', 'de 2023', 'de 2021'], smart: ['webOS, HDMI 2.1', 'Tizen, HDMI 2.1', 'Google TV', 'Android TV', 'Google TV'], detail: ['Support mural inclus.', 'Boîte d\'origine conservée.', 'Facture disponible.'] },
    pair: { marque: 'smart' },
    q: ['television living room wall', 'oled tv'], photos: [2, 3],
  }),
  V('image-son', 5, {
    title: '{produit} {marque} {modele}',
    desc: '{produit} {marque} {modele}, {detail}. {etat} {inclus}',
    price: [60, 890], cond: ['tres_bon_etat', 'bon_etat'],
    attrs: { type_produit: '{typeAttr}', marque: '{marque}' },
    opts: { produit: ['Casque', 'Enceinte', 'Appareil photo', 'Barre de son', 'Vidéoprojecteur'], typeAttr: ['Casque / Écouteurs', 'Enceinte', 'Appareil photo', 'Home cinéma', 'Vidéoprojecteur'], marque: ['Sony', 'Sonos', 'Canon', 'Samsung', 'Epson'], modele: ['WH-1000XM5', 'Era 100', 'EOS R50 + 18-45 mm', 'HW-Q700', 'EH-TW7100'], detail: ['réduction de bruit, 30 h d\'autonomie', 'Wi-Fi et Bluetooth, stéréo', 'hybride 24 Mpx, 1 200 déclenchements', '3.1.2 Dolby Atmos avec caisson', '4K PRO-UHD, 3 000 lumens, 400 h'], etat: ['Aucune trace.', 'Comme neuve.', 'Capteur nettoyé.', 'Très bon état.', 'Lampe à 15 % d\'usure.'], inclus: ['Étui et câbles inclus.', 'Câble d\'alimentation.', 'Batterie supplémentaire et sac.', 'Télécommande et câble HDMI.', 'Télécommande et câble.'] },
    pair: { produit: 'typeAttr', produit2: 'marque', produit3: 'modele', produit4: 'detail', produit5: 'etat', produit6: 'inclus' },
    q: ['sony headphones noise cancelling', 'sonos speaker shelf', 'canon mirrorless camera', 'soundbar tv', 'home projector'], qByOpt: 'produit', photos: [2, 3],
  }),
  V('image-son', 5, {
    title: '{produit} {marque}, {detail}',
    desc: '{produit} {marque}, {detail}. {etat} {origine}',
    price: [40, 520], cond: BON,
    attrs: { type_produit: '{typeAttr}', marque: '{marque}' },
    opts: { produit: ['Platine vinyle', 'Ampli hi-fi', 'Enceintes bibliothèque', 'Appareil photo argentique', 'Enceinte Bluetooth'], typeAttr: ['Autre', 'Autre', 'Enceinte', 'Appareil photo', 'Enceinte'], marque: ['Audio-Technica', 'Marantz', 'KEF', 'Olympus', 'JBL'], detail: ['LP120X, cellule neuve', 'PM6007 avec DAC', 'LS50 Meta (la paire)', 'OM-1 avec 50 mm f/1.8', 'Charge 5, étanche'], etat: ['Fonctionne parfaitement.', 'Aucun souffle.', 'Aucune trace sur les ébénisteries.', 'Cellule testée, joints changés.', 'Batterie tient 15 h.'], origine: ['Achetée en 2022.', 'Acheté en 2021.', 'Achetées en 2023.', 'Révisé par un spécialiste.', 'Achetée cet été.'] },
    pair: { produit: 'typeAttr', produit2: 'marque', produit3: 'detail', produit4: 'etat', produit5: 'origine' },
    q: ['turntable vinyl record player', 'hifi amplifier', 'bookshelf speakers', 'film camera vintage', 'bluetooth speaker'], qByOpt: 'produit', photos: [2, 3],
  }),

  // ---------------------------------------------------------------- Loisirs (80)
  V('livres', 6, {
    title: 'Lot de {nb} {genre}, {auteurs}',
    desc: 'Lot de {nb} livres {genreTxt} : {auteurs} et d\'autres. {format}, lus une fois, sans annotation ni page cornée. Vendus ensemble.',
    price: [10, 45], cond: BON,
    attrs: { genre: '{genreAttr}', auteur: '{auteurAttr}', format: '{formatAttr}' },
    opts: { nb: [8, 10, 12, 15, 20], genre: ['romans', 'polars', 'romans de science-fiction', 'BD', 'mangas', 'livres de cuisine'], genreTxt: ['contemporains', 'et thrillers', 'et fantasy', 'adultes', 'shōnen', 'illustrés'], genreAttr: ['Roman', 'Policier / Thriller', 'Science-fiction / Fantasy', 'BD / Manga', 'BD / Manga', 'Pratique / Cuisine'], auteurs: ['Leïla Slimani, Delphine de Vigan, Amélie Nothomb', 'Fred Vargas, Pierre Lemaitre, Franck Thilliez', 'Bernard Werber, Frank Herbert, Ursula Le Guin', 'Manu Larcenet, Riad Sattouf, Zep', 'One Piece tomes 1 à 20', 'Ottolenghi, Cyril Lignac, Marmiton'], auteurAttr: ['Divers', 'Divers', 'Divers', 'Divers', 'Eiichiro Oda', 'Divers'], format: ['Poche', 'Grand format', 'Poche', 'Albums cartonnés', 'Format poche', 'Beaux livres'], formatAttr: ['Poche', 'Grand format', 'Poche', 'Relié', 'Poche', 'Relié'] },
    pair: { genre: 'genreTxt', genre2: 'genreAttr', genre3: 'auteurs', genre4: 'auteurAttr', genre5: 'format', genre6: 'formatAttr' },
    q: ['paperback books stack', 'thriller novels pile', 'science fiction books', 'comic books bande dessinee', 'manga volumes', 'cookbooks stack'], qByOpt: 'genre', photos: [2, 3],
  }),
  V('livres', 6, {
    title: '{titre}',
    desc: '{titre}, {detail}. {etat} {raison}',
    price: [5, 60], cond: BON,
    attrs: { genre: '{genreAttr}', auteur: '{auteur}', format: '{formatAttr}' },
    opts: { titre: ['Manuels de prépa scientifique (lot)', 'Encyclopédie Larousse en 12 volumes', 'Beaux livres de photographie (lot de 4)', 'Livres jeunesse 3-6 ans (lot de 25)', 'Guides du Routard Europe (lot de 6)', 'Harry Potter, intégrale 7 tomes'], detail: ['maths, physique et chimie MPSI-MP, éditions Dunod', 'édition 2008 reliée, comme neuve', 'Doisneau, Salgado, Cartier-Bresson, National Geographic', 'albums cartonnés, T\'choupi, Petit Ours Brun, Kididoc', 'éditions 2022-2024', 'édition Gallimard reliée'], genreAttr: ['Scolaire / Universitaire', 'Autre', 'Beaux livres', 'Jeunesse', 'Pratique / Cuisine', 'Roman'], auteur: ['Divers', 'Larousse', 'Divers', 'Divers', 'Collectif', 'J. K. Rowling'], formatAttr: ['Grand format', 'Relié', 'Relié', 'Lot de livres', 'Poche', 'Relié'], etat: ['Quelques annotations au crayon.', 'Jamais ouverte.', 'Impeccables.', 'Quelques pages un peu usées.', 'Très bon état.', 'Jaquettes intactes.'], raison: ['Concours passés.', 'Manque de place.', 'Déménagement.', 'Les enfants ont grandi.', 'Voyages faits.', 'Relus trois fois, place aux suivants.'] },
    pair: { titre: 'detail', titre2: 'genreAttr', titre3: 'auteur', titre4: 'formatAttr', titre5: 'etat', titre6: 'raison' },
    q: ['textbooks stack university', 'encyclopedia volumes shelf', 'photography coffee table books', 'children picture books', 'travel guide books', 'harry potter books'], qByOpt: 'titre', photos: [2, 3],
  }),
  V('musique-instruments', 5, {
    title: 'Guitare {type} {marque} {modele}',
    desc: 'Guitare {type} {marque} {modele}, {detail}, cordes neuves. {etat} Vendue avec {inclus}. Essai possible à la maison.',
    price: [90, 1200], cond: BON,
    attrs: { type_instrument: 'Guitare', marque: '{marque}', niveau: '{niveau}' },
    opts: { type: ['acoustique', 'électrique', 'classique', 'électro-acoustique', 'électrique'], marque: ['Yamaha', 'Fender', 'Cordoba', 'Taylor', 'Gibson'], modele: ['FG800', 'Player Stratocaster', 'C5', 'GS Mini', 'Les Paul Studio'], detail: ['table en épicéa massif', 'micros single coil, vibrato', 'cordes nylon, idéale pour débuter', 'format voyage, micro ES2', 'micros humbucker, finition cherry'], etat: ['Aucune marque.', 'Une micro-rayure sur le corps.', 'État neuf.', 'Très bon état.', 'Frettes en parfait état.'], inclus: ['housse rembourrée', 'housse et câble jack', 'housse', 'housse Taylor', 'étui rigide'], niveau: ['Débutant', 'Intermédiaire', 'Débutant', 'Intermédiaire', 'Confirmé'] },
    pair: { type: 'marque', type2: 'modele', type3: 'detail', type4: 'inclus', type5: 'niveau' },
    q: ['acoustic guitar', 'fender stratocaster electric guitar', 'classical guitar nylon', 'taylor acoustic guitar', 'gibson les paul'], qByOpt: 'type', photos: [2, 3],
  }),
  V('musique-instruments', 5, {
    title: '{instrument} {marque} {modele}',
    desc: '{instrument} {marque} {modele}, {detail}. {etat} {inclus}',
    price: [120, 1900], cond: BON,
    attrs: { type_instrument: '{typeAttr}', marque: '{marque}', niveau: '{niveau}' },
    opts: { instrument: ['Piano numérique', 'Batterie électronique', 'Clavier arrangeur', 'Saxophone alto', 'Violon 4/4'], typeAttr: ['Piano / Clavier', 'Batterie / Percussions', 'Piano / Clavier', 'Vent', 'Cordes'], marque: ['Yamaha', 'Roland', 'Yamaha', 'Yamaha', 'Stentor'], modele: ['P-125', 'TD-07KV', 'PSR-E473', 'YAS-280', 'Student II'], detail: ['88 touches lestées, stand et pédale', 'peaux maillées, module avec coaching', '61 touches, 820 sonorités', 'laqué, bec Yamaha 4C', 'table en épicéa, archet et étui'], etat: ['Aucune touche abîmée.', 'Peaux et cymbales en très bon état.', 'Très bon état.', 'Révisé chez un luthier.', 'Cordes Dominant neuves.'], inclus: ['Casque inclus.', 'Tabouret et pédale inclus.', 'Pupitre et alimentation.', 'Étui et cordon.', 'Colophane et épaulière.'], niveau: ['Intermédiaire', 'Débutant', 'Débutant', 'Intermédiaire', 'Débutant'] },
    pair: { instrument: 'typeAttr', instrument2: 'marque', instrument3: 'modele', instrument4: 'detail', instrument5: 'etat', instrument6: 'inclus', instrument7: 'niveau' },
    q: ['digital piano home', 'electronic drum kit', 'keyboard synthesizer', 'alto saxophone', 'violin bow case'], qByOpt: 'instrument', photos: [2, 3],
  }),
  V('musique-instruments', 5, {
    title: 'Lot de {nb} vinyles {genre}',
    desc: 'Lot de {nb} vinyles {genre} : {artistes}. Pochettes et disques en {etat}, pressages {pressage}. Vendus en lot.',
    price: [40, 220], cond: BON,
    attrs: { type_instrument: 'Vinyles / CD', marque: 'Divers' },
    opts: { nb: [15, 20, 30, 40], genre: ['rock', 'jazz', 'rap français', 'chanson française', 'soul et funk'], artistes: ['Pink Floyd, Led Zeppelin, The Beatles', 'Miles Davis, Coltrane, Bill Evans', 'IAM, NTM, MC Solaar', 'Brel, Brassens, Barbara', 'Marvin Gaye, James Brown, Stevie Wonder'], etat: ['très bon état', 'bon état', 'état correct'], pressage: ['d\'époque', 'récents', 'mixtes'] },
    pair: { genre: 'artistes' },
    q: ['vinyl records collection', 'vinyl records crate'], photos: [2, 3],
  }),
  V('sports-hobbies', 6, {
    title: '{article} {marque} {detail}',
    desc: '{article} {marque}, {detail}, {etat}. {usage} {inclus}',
    price: [40, 890], cond: BON,
    attrs: { sport: '{sport}', univers: 'Mixte', marque: '{marque}', type_produit: 'Matériel' },
    opts: { article: ['Vélo d\'appartement', 'Tapis de course', 'Rameur', 'Banc de musculation', 'Set d\'haltères', 'Home trainer'], sport: ['Fitness / Musculation', 'Fitness / Musculation', 'Fitness / Musculation', 'Fitness / Musculation', 'Fitness / Musculation', 'Cyclisme'], marque: ['Domyos', 'NordicTrack', 'Concept2', 'Domyos', 'Bowflex', 'Tacx'], detail: ['EB 500, connecté', 'T 6.5 S, inclinaison', 'modèle D, moniteur PM5', 'BM 900, réglable', 'SelectTech 552 (la paire)', 'Flux 2, connecté Zwift'], etat: ['très bon état', 'bon état', 'peu servi', 'très bon état', 'comme neuf', 'très bon état'], usage: ['Utilisé un hiver.', 'Utilisé deux fois par semaine pendant un an.', 'Servi 6 mois.', 'Monté et utilisé l\'hiver dernier.', 'Peu utilisés.', 'Deux saisons.'], inclus: ['Notice incluse.', 'Clé de sécurité incluse.', 'Se sépare en deux pour le transport.', 'Barre incluse.', 'Support inclus.', 'Câble et axe inclus.'] },
    pair: { article: 'sport', article2: 'marque', article3: 'detail', article4: 'etat', article5: 'usage', article6: 'inclus' },
    q: ['exercise bike home', 'treadmill home gym', 'rowing machine', 'weight bench', 'adjustable dumbbells', 'bike trainer indoor'], qByOpt: 'article', photos: [2, 3],
  }),
  V('sports-hobbies', 6, {
    title: '{article} {marque} {taille}',
    desc: '{article} {marque} {taille}, {detail}. {etat} {saison}',
    price: [40, 590], cond: BON,
    attrs: { sport: '{sport}', univers: '{univers}', marque: '{marque}', type_produit: '{typeAttr}' },
    opts: { article: ['Skis de piste', 'Snowboard', 'Planche de surf', 'Raquettes de tennis (lot de 2)', 'Combinaison de plongée', 'Sac de randonnée'], sport: ['Ski / Snowboard', 'Ski / Snowboard', 'Sports de glisse (surf, skate)', 'Tennis / Padel / Badminton', 'Natation / Plongée', 'Randonnée / Trekking'], marque: ['Rossignol', 'Burton', 'Torq', 'Wilson', 'Cressi', 'Osprey'], taille: ['170 cm', '155 cm', '7\'2"', 'grip 3', 'taille M', '65 L'], detail: ['fixations Look, semelles fartées', 'fixations Union, boots 42 incluses', 'mini-malibu, leash et housse', 'Blade 98, cordées', '5 mm, portée deux saisons', 'Atmos AG, dos ventilé'], etat: ['Carres affûtées.', 'Semelle sans rayure.', 'Un pet réparé proprement.', 'Bon état.', 'Néoprène souple.', 'Comme neuf.'], saison: ['Prêts pour cet hiver.', 'Prêt pour la saison.', 'Idéale pour débuter.', 'Idéales pour un duo.', 'Idéale pour la Méditerranée.', 'Pour les longues randonnées.'], univers: ['Mixte', 'Mixte', 'Mixte', 'Mixte', 'Homme', 'Mixte'], typeAttr: ['Matériel', 'Matériel', 'Matériel', 'Matériel', 'Vêtement', 'Accessoire'] },
    pair: { article: 'sport', article2: 'marque', article3: 'taille', article4: 'detail', article5: 'etat', article6: 'saison', article7: 'univers', article8: 'typeAttr' },
    q: ['alpine skis', 'snowboard', 'surfboard beach', 'tennis rackets', 'wetsuit diving', 'hiking backpack'], qByOpt: 'article', photos: [2, 3],
  }),
  V('sports-hobbies', 6, {
    title: '{article} {marque}, {detail}',
    desc: '{article} {marque}, {detail}. {etat} {raison}',
    price: [25, 350], cond: BON,
    attrs: { sport: '{sport}', univers: 'Mixte', marque: '{marque}', type_produit: '{typeAttr}' },
    opts: { article: ['Trottinette électrique', 'Tente 4 places', 'Kit de golf complet', 'Paddle gonflable', 'Table de ping-pong', 'Ballon et équipement de football'], sport: ['Autre', 'Randonnée / Trekking', 'Autre', 'Natation / Plongée', 'Tennis / Padel / Badminton', 'Football'], marque: ['Xiaomi', 'Quechua', 'Callaway', 'Itiwit', 'Cornilleau', 'Nike'], detail: ['Mi Electric Scooter 3, 30 km d\'autonomie', '2 chambres, montage 10 min', 'fers, bois, putter et sac', '10\'6", pompe et pagaie', 'extérieure pliable 250 S', 'ballon taille 5, protège-tibias, gants de gardien'], etat: ['Batterie en bonne santé.', 'Aucune déchirure, imperméable.', 'Grips changés.', 'Aucune fuite.', 'Plateau sans rayure.', 'Bon état.'], raison: ['Je passe au vélo.', 'On a acheté plus grand.', 'J\'arrête le golf.', 'Manque de place.', 'Déménagement.', 'Les enfants ont grandi.'], typeAttr: ['Matériel', 'Matériel', 'Matériel', 'Matériel', 'Matériel', 'Accessoire'] },
    pair: { article: 'sport', article2: 'marque', article3: 'detail', article4: 'etat', article5: 'raison', article6: 'typeAttr' },
    q: ['electric scooter city', 'camping tent', 'golf clubs bag', 'stand up paddle board', 'ping pong table outdoor', 'football ball equipment'], qByOpt: 'article', photos: [2, 3],
  }),
  V('velos', 6, {
    title: 'VTT {marque} {modele} taille {taille}',
    desc: 'VTT {marque} {modele} taille {taille}, roues {roues}, {transmission}, freins à disque hydrauliques. {etat} Révisé récemment, {detail}.',
    price: [250, 1900], cond: BON,
    attrs: { type_velo: 'VTT', taille_cadre: '{taille}', roues: '{roues}', materiau: '{materiau}', marque: '{marque}' },
    opts: { marque: ['Rockrider', 'Trek', 'Specialized', 'Scott', 'Giant', 'Canyon'], modele: ['ST 540', 'Marlin 7', 'Rockhopper', 'Aspect 950', 'Talon 2', 'Grand Canyon 7'], taille: ['M', 'L', 'S', 'XL'], roues: ['27,5"', '29"', '29"'], transmission: ['Shimano Deore 1x12', 'Shimano Altus 2x9', 'SRAM SX 1x12', 'Shimano 3x8'], materiau: ['Aluminium', 'Aluminium', 'Carbone', 'Aluminium'], etat: ['Cadre sans choc.', 'Quelques éraflures sur la peinture.', 'Très bon état.'], detail: ['chaîne et plaquettes neuves', 'pneus tubeless récents', 'câbles changés'] },
    pair: { marque: 'modele' },
    q: ['mountain bike trail', 'mountain bike hardtail'], photos: [2, 4],
  }),
  V('velos', 6, {
    title: 'Vélo électrique {marque} {modele}',
    desc: 'Vélo électrique {marque} {modele}, batterie {batterie}, {km} km, moteur {moteur}. {etat} Vendu avec chargeur, antivol et {inclus}. Essai possible.',
    price: [700, 2400], cond: BON,
    attrs: { type_velo: 'Électrique', taille_cadre: '{taille}', roues: '28"', materiau: 'Aluminium', marque: '{marque}' },
    opts: { marque: ['Decathlon', 'Moustache', 'Cowboy', 'Giant', 'Cube', 'Gazelle'], modele: ['Elops 920 E', 'Lundi 27', 'Cruiser 4', 'Explore E+', 'Touring Hybrid', 'Ultimate C380'], batterie: ['418 Wh', '500 Wh', '360 Wh', '500 Wh', '625 Wh', '500 Wh'], km: [1200, 2400, 3100, 4500, 900, 2800], moteur: ['central', 'Bosch Performance', 'dans la roue arrière', 'Yamaha SyncDrive', 'Bosch Active Plus', 'Bosch Performance'], taille: ['M', 'L', 'S', 'M'], etat: ['Batterie à 95 %.', 'Batterie révisée.', 'Comme neuf.', 'Très bon état.'], inclus: ['sacoche', 'porte-bagages', 'panier avant', 'garde-boue'] },
    pair: { marque: 'modele', marque2: 'batterie', marque3: 'moteur' },
    q: ['electric bike city', 'ebike commuter'], photos: [2, 4],
  }),
  V('velos', 4, {
    title: 'Vélo de route {marque} {modele} {taille}',
    desc: 'Vélo de route {marque} {modele} taille {taille}, cadre {materiau}, groupe {groupe}, roues {roues}. {km} km, {etat}. Pédales {pedales} incluses.',
    price: [500, 2900], cond: BON,
    attrs: { type_velo: 'Route', taille_cadre: '{taille}', roues: '28"', materiau: '{Materiau}', marque: '{marque}' },
    opts: { marque: ['Triban', 'Trek', 'Canyon', 'Specialized'], modele: ['RC 520', 'Domane AL 3', 'Endurace CF 7', 'Allez Sprint'], taille: ['M', 'L', 'S'], materiau: ['aluminium', 'aluminium', 'carbone', 'aluminium'], groupe: ['Shimano 105', 'Shimano Tiagra', 'Shimano Ultegra', 'Shimano 105'], roues: ['Mavic Aksium', 'Bontrager', 'DT Swiss', 'Roval'], km: [3000, 5000, 4200, 2500], etat: ['jamais tombé', 'quelques éclats de peinture', 'très bon état'], pedales: ['Look Keo', 'Shimano SPD', 'automatiques'] },
    pair: { marque: 'modele', marque2: 'materiau', marque3: 'groupe', marque4: 'roues' },
    q: ['road bike carbon', 'road bicycle wall'], photos: [2, 3],
  }),
  V('velos', 4, {
    title: 'Vélo enfant {marque} {roues} pouces, {age}',
    desc: 'Vélo enfant {marque} {roues} pouces pour {age}, {couleur}, {detail}. {etat} Notre enfant est passé à la taille supérieure.',
    price: [40, 190], cond: BON,
    attrs: { type_velo: 'Enfant', taille_cadre: 'Enfant', roues: '{rouesAttr}', marque: '{marque}' },
    opts: { marque: ['Btwin', 'Puky', 'Woom', 'Early Rider'], roues: [16, 20, 24, 14], rouesAttr: ['16"', '20"', '24"', '14"'], age: ['4-6 ans', '6-9 ans', '9-12 ans', '3-5 ans'], couleur: ['rouge', 'bleu', 'vert', 'rose'], detail: ['petites roues incluses', '6 vitesses, garde-boue', '7 vitesses, béquille', 'ultra-léger, sans vitesse'], etat: ['Pneus neufs.', 'Très bon état.', 'Quelques rayures.', 'Comme neuf.'] },
    pair: { roues: 'rouesAttr', roues2: 'age', roues3: 'detail' },
    q: ['kids bike', 'children bicycle'], photos: [2, 3],
  }),
  V('jeux-jouets', 5, {
    title: 'Lego {theme} {set}',
    desc: 'Lego {theme} {set}, {pieces} pièces, complet avec notice{boite}. Monté une fois et exposé, démonté et trié par sachets pour la vente. Aucune pièce manquante (vérifié).',
    price: [40, 320], cond: ['tres_bon_etat', 'bon_etat'],
    attrs: { age: '{age}', type_jouet: 'Construction', marque: 'Lego' },
    opts: { theme: ['Technic', 'Star Wars', 'Harry Potter', 'City', 'Creator Expert'], set: ['Bugatti Chiron', 'Faucon Millenium', 'Château de Poudlard', 'Caserne de pompiers', 'Fleuriste'], pieces: [3599, 1353, 6020, 509, 2350], age: ['10 ans et plus', '10 ans et plus', '10 ans et plus', '6-9 ans', '10 ans et plus'], boite: [' et boîte', '', ' et boîte d\'origine'] },
    pair: { theme: 'set', theme2: 'pieces', theme3: 'age' },
    q: ['lego technic car', 'lego star wars', 'lego harry potter castle', 'lego city set', 'lego creator building'], qByOpt: 'theme', photos: [2, 3],
  }),
  V('jeux-jouets', 5, {
    title: '{jouet}, {detail}',
    desc: '{jouet}, {detail}. {etat} {raison}',
    price: [15, 160], cond: BON,
    attrs: { age: '{age}', type_jouet: '{typeAttr}', marque: '{marque}' },
    opts: { jouet: ['Lot de 10 jeux de société', 'Cuisine en bois enfant', 'Playmobil (lot)', 'Trampoline 3 m', 'Puzzles 1 000 pièces (lot de 6)'], typeAttr: ['Jeu de société', 'Éveil', 'Poupée / Figurine', 'Plein air', 'Puzzle'], marque: ['Asmodee', 'Janod', 'Playmobil', 'Décathlon', 'Ravensburger'], detail: ['Catan, Dixit, 7 Wonders, Codenames, Azul…', 'avec accessoires et dînette', 'maison, château, véhicules, plus de 40 personnages', 'filet de sécurité et échelle', 'paysages et villes'], age: ['10 ans et plus', '3-5 ans', '6-9 ans', '6-9 ans', '10 ans et plus'], etat: ['Complets, vérifiés.', 'Peinture intacte.', 'Trié et complet.', 'Ressorts et tapis en bon état.', 'Complets, comptés.'], raison: ['On fait de la place.', 'Nos enfants ont grandi.', 'Fin de collection.', 'Déménagement en appartement.', 'Déjà faits deux fois.'] },
    pair: { jouet: 'typeAttr', jouet2: 'marque', jouet3: 'detail', jouet4: 'age', jouet5: 'etat', jouet6: 'raison' },
    q: ['board games stack', 'wooden play kitchen', 'playmobil toys', 'garden trampoline', 'jigsaw puzzle boxes'], qByOpt: 'jouet', photos: [2, 3],
  }),
  V('collection', 5, {
    title: '{objet}, {detail}',
    desc: '{objet}, {detail}. {etat} {origine} Vente en main propre uniquement.',
    price: [30, 450], cond: BON,
    attrs: { type_collection: '{typeAttr}' },
    opts: { objet: ['Collection de pièces de 2 € commémoratives', 'Album de timbres France 1960-1990', 'Lot de cartes Pokémon', 'Figurines Star Wars vintage', 'Machine à écrire Olivetti'], typeAttr: ['Monnaies', 'Timbres', 'Cartes', 'Figurines', 'Vintage'], detail: ['120 pièces de 15 pays, classées', 'plus de 800 timbres oblitérés', '300 cartes dont 15 holographiques', '12 figurines Kenner années 80', 'Lettera 32 avec housse'], etat: ['Neuves sous capsule.', 'Album en bon état.', 'Cartes protégées sous sleeves.', 'Peinture d\'origine.', 'Fonctionne, ruban neuf.'], origine: ['Collection constituée depuis 2004.', 'Héritage familial.', 'Collection de mon adolescence.', 'Collection personnelle.', 'Chinée en brocante.'] },
    pair: { objet: 'typeAttr', objet2: 'detail', objet3: 'etat', objet4: 'origine' },
    q: ['coin collection album', 'stamp collection album', 'pokemon cards', 'vintage action figures', 'olivetti typewriter'], qByOpt: 'objet', photos: [2, 3],
  }),
];
