// Archétypes d'annonces (AUDIT §71) — mode, famille, animaux.
const V = (slug, n, def) => ({ slug, n, ...def });
const BON = ['bon_etat', 'tres_bon_etat'];

module.exports = [
  // ---------------------------------------------------------------- Mode (90)
  V('vetements', 6, {
    title: 'Manteau {matiere} {marque} taille {taille}, {couleur}',
    desc: 'Manteau {coupe} en {matiere} {marque}, taille {taille}, couleur {couleur}. Porté {porte}, aucune trace d\'usure, doublure impeccable. Boutons et poches d\'origine. Vendu car je ne le porte plus.',
    price: [45, 190], cond: ['tres_bon_etat', 'bon_etat'],
    attrs: { univers: 'Femme', type_vetement: 'Manteau / Veste', taille: '{taille}', marque: '{marque}', couleur: '{Couleur}', matiere: '{matiere}' },
    opts: { matiere: ['laine', 'laine et cachemire', 'drap de laine'], marque: ['Sézane', 'Comptoir des Cotonniers', 'Zara', 'Maje', 'Mango', 'Sandro'], taille: ['36', '38', '40', '42'], couleur: ['camel', 'noir', 'gris', 'beige', 'bordeaux'], coupe: ['long', 'droit', 'oversize', 'cintré'], porte: ['une saison', 'deux hivers', 'quelques fois'] },
    q: ['wool coat woman', 'camel coat fashion'], photos: [2, 4],
  }),
  V('vetements', 6, {
    title: 'Veste {type} {marque} homme, taille {taille}',
    desc: 'Veste {type} {marque} pour homme, taille {taille}, {couleur}. {detail} État {etat}, lavée et prête à porter. Pas d\'échange.',
    price: [25, 160], cond: BON,
    attrs: { univers: 'Homme', type_vetement: 'Manteau / Veste', taille: '{taille}', marque: '{marque}', couleur: '{Couleur}', matiere: '{matiere}' },
    opts: { type: ['en jean', 'bomber', 'doudoune légère', 'blazer', 'imperméable'], marque: ['Levi\'s', 'Alpha Industries', 'Uniqlo', 'Celio', 'The North Face', 'Jules'], taille: ['M', 'L', 'XL', 'S'], couleur: ['bleu', 'noir', 'vert', 'beige', 'gris'], matiere: ['coton', 'nylon', 'polyester', 'laine mélangée', 'coton'], detail: ['Coupe ajustée, poches zippées.', 'Modèle classique, doublure orange.', 'Compressible dans sa pochette.', 'Deux boutons, doublure intérieure.', 'Capuche amovible, coutures étanches.'], etat: ['impeccable', 'très bon', 'bon'] },
    pair: { type: 'matiere', type2: 'detail' },
    q: ['denim jacket men', 'bomber jacket', 'men blazer jacket'], photos: [2, 4],
  }),
  V('vetements', 6, {
    title: 'Robe {style} {marque} taille {taille}',
    desc: 'Robe {style} {marque}, taille {taille}, {couleur}, {matiere}. Portée {porte} pour une occasion, nettoyée depuis. {detail} Envoi impossible, remise en main propre.',
    price: [20, 120], cond: ['tres_bon_etat', 'bon_etat', 'neuf'],
    attrs: { univers: 'Femme', type_vetement: 'Robe', taille: '{taille}', marque: '{marque}', couleur: '{Couleur}', matiere: '{matiere}' },
    opts: { style: ['longue fleurie', 'de soirée', 'chemise', 'portefeuille', 'en maille'], marque: ['Sézane', 'Ba&sh', 'Zara', 'H&M', 'Kiabi', 'Naf Naf'], taille: ['34', '36', '38', '40', '42'], couleur: ['bleu', 'noir', 'vert', 'rouge', 'beige'], matiere: ['viscose', 'satin', 'coton', 'lin', 'laine'], porte: ['une fois', 'deux fois', 'trois fois'], detail: ['Étiquette encore présente.', 'Ceinture d\'origine incluse.', 'Fermeture éclair invisible dans le dos.'] },
    pair: { style: 'matiere' },
    q: ['floral dress woman', 'evening dress fashion', 'summer dress'], photos: [2, 4],
  }),
  V('vetements', 6, {
    title: 'Jean {marque} {modele} {taille}',
    desc: 'Jean {marque} {modele}, taille {taille} ({tailleFr}), {couleur}, {coupe}. Acheté {achat}, porté {porte}. Aucun trou ni tache, boutons et rivets d\'origine.',
    price: [15, 70], cond: BON,
    attrs: { univers: '{univers}', type_vetement: 'Pantalon / Jean', taille: '{tailleFr}', marque: '{marque}', couleur: '{Couleur}', matiere: 'denim' },
    opts: { marque: ['Levi\'s', 'Levi\'s', 'Diesel', 'Nudie', 'Uniqlo', 'Weekday'], modele: ['501', '511 slim', 'D-Strukt', 'Lean Dean', 'Selvedge', 'Rowe'], taille: ['W30 L32', 'W31 L32', 'W32 L34', 'W33 L32', 'W34 L32', 'W28 L30'], tailleFr: ['40', '40', '42', '42', '44', '38'], couleur: ['bleu', 'noir', 'gris', 'bleu'], coupe: ['coupe droite', 'coupe slim', 'coupe regular', 'coupe ample'], univers: ['Homme', 'Homme', 'Femme', 'Unisexe'], achat: ['l\'an dernier', 'il y a deux ans', 'cet hiver'], porte: ['une dizaine de fois', 'régulièrement', 'très peu'] },
    pair: { marque: 'modele', taille: 'tailleFr' },
    q: ['jeans denim folded', 'levis jeans'], photos: [2, 3],
  }),
  V('vetements', 5, {
    title: 'Pull {matiere} {marque} {taille}, {couleur}',
    desc: 'Pull en {matiere} {marque}, taille {taille}, {couleur}, col {col}. Doux et chaud, lavé à la main, aucune bouloche. Parfait pour l\'hiver qui arrive.',
    price: [18, 95], cond: ['tres_bon_etat', 'bon_etat'],
    attrs: { univers: '{univers}', type_vetement: 'Pull / Gilet', taille: '{taille}', marque: '{marque}', couleur: '{Couleur}', matiere: '{matiere}' },
    opts: { matiere: ['laine mérinos', 'cachemire', 'coton', 'mohair', 'laine'], marque: ['Uniqlo', 'Eric Bompard', 'Petit Bateau', 'Monoprix', 'Armor Lux'], taille: ['S', 'M', 'L', 'XL'], couleur: ['gris', 'bleu', 'beige', 'vert', 'bordeaux'], col: ['rond', 'V', 'roulé'], univers: ['Femme', 'Homme', 'Unisexe'] },
    q: ['wool sweater folded', 'knit sweater'], photos: [2, 3],
  }),
  V('vetements', 5, {
    title: 'Lot de {nb} t-shirts et tops {taille}',
    desc: 'Lot de {nb} t-shirts et tops taille {taille} ({marques}), couleurs variées, {etat}. Vendus ensemble uniquement, idéal pour renouveler sa garde-robe à petit prix. Lavés et repassés.',
    price: [12, 40], cond: BON,
    attrs: { univers: '{univers}', type_vetement: 'T-shirt / Top', taille: '{taille}', marque: '{marque}', matiere: 'coton' },
    opts: { nb: [5, 6, 8, 10], taille: ['S', 'M', 'L', '38', '40'], marques: ['H&M, Zara, Uniqlo', 'Celio, Jules, Kiabi', 'Mango, Promod'], marque: ['Divers', 'Divers', 'Divers'], etat: ['bon état général', 'très bon état, deux jamais portés', 'bon état'], univers: ['Femme', 'Homme', 'Femme'] },
    pair: { marques: 'univers' },
    q: ['folded t-shirts stack', 'clothes pile colorful'], photos: [2, 3],
  }),
  V('vetements', 5, {
    title: 'Costume {marque} {taille} {couleur}',
    desc: 'Costume deux pièces {marque}, veste {taille} et pantalon {taillePant}, {couleur}, {matiere}. Porté {porte} pour un mariage, nettoyé au pressing. Coupe {coupe}, doublure intacte.',
    price: [60, 260], cond: ['tres_bon_etat', 'bon_etat'],
    attrs: { univers: 'Homme', type_vetement: 'Costume', taille: '{taille}', marque: '{marque}', couleur: '{Couleur}', matiere: '{matiere}' },
    opts: { marque: ['Hugo Boss', 'The Kooples', 'De Fursac', 'Celio', 'Zara Man'], taille: ['48', '50', '52', '46'], taillePant: ['40', '42', '44', '38'], couleur: ['bleu', 'gris', 'noir'], matiere: ['laine', 'laine mélangée', 'coton stretch'], porte: ['une fois', 'deux fois'], coupe: ['slim', 'regular', 'ajustée'] },
    pair: { taille: 'taillePant' },
    q: ['men suit jacket', 'navy suit hanging'], photos: [2, 3],
  }),
  V('vetements', 6, {
    title: 'Lot vêtements {univers} {age}, {saison}',
    desc: 'Lot de {nb} pièces pour {univers} {age} ({contenu}), marques {marques}, {saison}. Vêtements propres, sans tache, triés par taille. Prix pour le lot complet.',
    price: [15, 55], cond: BON,
    attrs: { univers: '{univAttr}', type_vetement: 'Autre', taille: '{taille}', marque: 'Divers' },
    opts: { univers: ['fille', 'garçon'], univAttr: ['Fille', 'Garçon'], age: ['4 ans', '6 ans', '8 ans', '10 ans'], taille: ['XXS', 'XS', 'XS', 'S'], nb: [12, 15, 18, 20], contenu: ['pantalons, pulls, t-shirts', 'robes, leggings, gilets', 'joggings, sweats, t-shirts'], marques: ['Okaïdi, Vertbaudet, Kiabi', 'Petit Bateau, Zara Kids, H&M', 'Décathlon, Kiabi, Tape à l\'œil'], saison: ['automne-hiver', 'printemps-été', 'toutes saisons'] },
    pair: { univers: 'univAttr', age: 'taille' },
    q: ['kids clothes folded', 'children clothing pile'], photos: [2, 3],
  }),
  V('chaussures', 7, {
    title: 'Baskets {marque} {modele} pointure {pointure}',
    desc: 'Baskets {marque} {modele} pointure {pointure}, {couleur}. Portées {porte}, semelles {semelle}, lacets d\'origine, boîte fournie. Aucun défaut visible, voir les photos.',
    price: [35, 140], cond: ['tres_bon_etat', 'bon_etat', 'neuf'],
    attrs: { univers: '{univers}', pointure: '{pointure}', marque: '{marque}', couleur: '{Couleur}' },
    opts: { marque: ['Nike', 'Adidas', 'New Balance', 'Veja', 'Puma', 'Asics', 'Converse'], modele: ['Air Force 1', 'Stan Smith', '574', 'V-10', 'Suede', 'Gel-Kayano', 'Chuck 70'], pointure: [38, 39, 40, 41, 42, 43, 44], couleur: ['blanc', 'noir', 'gris', 'beige', 'bleu'], univers: ['Homme', 'Femme', 'Unisexe'], porte: ['quelques fois', 'un été', 'très peu'], semelle: ['quasi neuves', 'propres', 'à peine marquées'] },
    pair: { marque: 'modele' },
    q: ['white sneakers', 'sneakers pair floor', 'running shoes'], photos: [2, 4],
  }),
  V('chaussures', 5, {
    title: 'Bottines cuir {marque} pointure {pointure}',
    desc: 'Bottines en cuir {marque} pointure {pointure}, {couleur}, {type}. Semelles {semelle}, cuir nourri régulièrement. Portées deux hivers, encore belles. Vendues avec embauchoirs.',
    price: [45, 190], cond: BON,
    attrs: { univers: '{univers}', pointure: '{pointure}', marque: '{marque}', couleur: '{Couleur}' },
    opts: { marque: ['Dr. Martens', 'Clarks', 'Minelli', 'Jonak', 'Timberland'], pointure: [37, 38, 39, 40, 41, 42, 43], couleur: ['noir', 'marron', 'bordeaux'], type: ['à lacets', 'chelsea', 'à zip'], semelle: ['ressemelées l\'an dernier', 'd\'origine, peu usées', 'crantées'], univers: ['Femme', 'Homme', 'Unisexe'] },
    q: ['leather boots', 'chelsea boots leather'], photos: [2, 3],
  }),
  V('chaussures', 4, {
    title: 'Chaussures de randonnée {marque} {pointure}',
    desc: 'Chaussures de randonnée {marque} {modele} pointure {pointure}, membrane {membrane}, tige {tige}. Utilisées {usage}, semelles Vibram en bon état. Vendues avec lacets de rechange.',
    price: [40, 130], cond: BON,
    attrs: { univers: '{univers}', pointure: '{pointure}', marque: '{marque}', couleur: '{Couleur}' },
    opts: { marque: ['Salomon', 'Meindl', 'Lowa', 'Merrell'], modele: ['X Ultra 4', 'Kansas', 'Renegade', 'Moab 3'], pointure: [39, 41, 42, 43, 44, 45], membrane: ['Gore-Tex', 'imperméable', 'Gore-Tex'], tige: ['mi-haute', 'haute', 'basse'], usage: ['trois randonnées', 'une saison en montagne', 'une semaine de GR'], couleur: ['gris', 'marron', 'vert', 'noir'], univers: ['Homme', 'Femme', 'Unisexe'] },
    pair: { marque: 'modele' },
    q: ['hiking boots', 'trekking shoes mountain'], photos: [2, 3],
  }),
  V('chaussures', 4, {
    title: 'Escarpins {marque} pointure {pointure}, {couleur}',
    desc: 'Escarpins {marque} pointure {pointure}, {couleur}, talon {talon} cm, cuir {cuir}. Portés une fois pour une cérémonie, semelles intactes. Boîte et pochon fournis.',
    price: [35, 220], cond: ['tres_bon_etat', 'neuf'],
    attrs: { univers: 'Femme', pointure: '{pointure}', marque: '{marque}', couleur: '{Couleur}' },
    opts: { marque: ['Repetto', 'Jonak', 'Minelli', 'Bocage'], pointure: [36, 37, 38, 39, 40], couleur: ['noir', 'rouge', 'beige', 'bordeaux'], talon: [5, 7, 8], cuir: ['verni', 'lisse', 'daim'] },
    q: ['high heels shoes', 'elegant pumps shoes'], photos: [2, 3],
  }),
  V('accessoires-bagagerie', 5, {
    title: 'Sac {type} {marque} {couleur}',
    desc: 'Sac {type} {marque} en {matiere}, {couleur}, {dim}. {detail} Intérieur propre, fermetures fonctionnelles, {usure}. Vendu avec sa housse.',
    price: [30, 260], cond: BON,
    attrs: { type_accessoire: 'Sac', marque: '{marque}' },
    opts: { type: ['cabas', 'à main', 'à dos', 'bandoulière', 'week-end'], marque: ['Longchamp', 'Lancaster', 'Fjällräven', 'Sézane', 'Eastpak'], matiere: ['cuir', 'toile enduite', 'toile', 'cuir grainé', 'nylon'], couleur: ['noir', 'camel', 'bleu marine', 'vert', 'bordeaux'], dim: ['grand format', 'format moyen', 'format A4'], detail: ['Anses en cuir, fermeture aimantée.', 'Poche zippée intérieure et porte-clés.', 'Compartiment ordinateur 15".', 'Bandoulière réglable amovible.', 'Poche latérale et double fermeture.'], usure: ['légères traces sur les coins', 'aucune usure', 'patine naturelle du cuir'] },
    pair: { type: 'detail' },
    q: ['leather handbag', 'tote bag', 'backpack canvas'], photos: [2, 4],
  }),
  V('accessoires-bagagerie', 4, {
    title: 'Valise {marque} {taille} {couleur}',
    desc: 'Valise {marque} {taille} ({dim}), {couleur}, coque {coque}, 4 roues doubles, serrure TSA. Utilisée pour {usage}, quelques rayures d\'usage sur la coque, roues et poignée parfaites.',
    price: [40, 190], cond: BON,
    attrs: { type_accessoire: 'Valise', marque: '{marque}' },
    opts: { marque: ['Samsonite', 'Delsey', 'American Tourister', 'Rimowa'], taille: ['cabine', 'moyenne', 'grande'], dim: ['55 cm', '66 cm', '75 cm'], couleur: ['noir', 'bleu', 'gris', 'argent'], coque: ['rigide polycarbonate', 'souple', 'rigide'], usage: ['deux voyages', 'un an de déplacements pro', 'trois vacances'] },
    pair: { taille: 'dim' },
    q: ['suitcase luggage', 'travel suitcase wheels'], photos: [2, 3],
  }),
  V('accessoires-bagagerie', 4, {
    title: '{accessoire} {marque}, {etat}',
    desc: '{accessoire} {marque}, {couleur}, {detail}. {etat2} Vendu avec {inclus}.',
    price: [15, 160], cond: BON,
    attrs: { type_accessoire: '{typeAttr}', marque: '{marque}' },
    opts: { accessoire: ['Lunettes de soleil', 'Écharpe en cachemire', 'Ceinture en cuir', 'Chapeau panama'], typeAttr: ['Lunettes', 'Écharpe / Foulard', 'Ceinture', 'Chapeau / Bonnet'], marque: ['Ray-Ban', 'Eric Bompard', 'Le Tanneur', 'Borsalino'], couleur: ['monture noire, verres verts', 'gris chiné', 'marron', 'beige'], detail: ['modèle Wayfarer, verres sans rayure', '180 × 30 cm, très douce', 'taille 95, boucle argentée', 'taille 58, ruban noir'], etat: ['état neuf', 'très bon état', 'bon état', 'comme neuf'], etat2: ['Portées quelques week-ends.', 'Portée un hiver.', 'Portée régulièrement, cuir intact.', 'Porté une saison.'], inclus: ['étui et chiffon', 'sa pochette', 'sa boîte', 'sa boîte de transport'] },
    pair: { accessoire: 'typeAttr', accessoire2: 'marque', accessoire3: 'couleur', accessoire4: 'detail', accessoire5: 'etat2', accessoire6: 'inclus' },
    q: ['sunglasses ray-ban', 'cashmere scarf', 'leather belt', 'panama hat'], qByOpt: 'accessoire', photos: [2, 3],
  }),
  V('montres-bijoux', 6, {
    title: 'Montre {marque} {modele}, {mouvement}',
    desc: 'Montre {marque} {modele}, mouvement {mouvement}, boîtier {boitier} mm, bracelet {bracelet}. Achetée {achat}, {etat}. Vendue avec boîte, papiers et facture. Remise en main propre dans un lieu public.',
    price: [90, 1400], cond: ['tres_bon_etat', 'bon_etat'],
    attrs: { type_bijou: 'Montre', marque: '{marque}', matiere: 'Acier' },
    opts: { marque: ['Seiko', 'Tissot', 'Casio', 'Citizen', 'Orient', 'Swatch'], modele: ['5 Sports', 'PRX', 'G-Shock', 'Eco-Drive', 'Bambino', 'Sistem51'], mouvement: ['automatique', 'quartz', 'automatique', 'solaire'], boitier: [38, 40, 42], bracelet: ['acier', 'cuir', 'nylon', 'caoutchouc'], achat: ['en 2023', 'l\'an dernier', 'en 2022'], etat: ['aucune rayure', 'micro-rayures sur le bracelet', 'verre impeccable'] },
    pair: { marque: 'modele' },
    q: ['wristwatch automatic', 'watch close up wrist'], photos: [2, 4],
  }),
  V('montres-bijoux', 6, {
    title: '{bijou} {matiere} {detail}',
    desc: '{bijou} en {matiere}, {detail}, {taille}. {origine} Poinçon visible sur la photo. Remise en main propre uniquement, dans un lieu public.',
    price: [25, 650], cond: ['tres_bon_etat', 'bon_etat', 'neuf'],
    attrs: { type_bijou: '{typeAttr}', marque: '{marque}', matiere: '{matAttr}' },
    opts: { bijou: ['Bague', 'Collier', 'Bracelet', 'Boucles d\'oreilles', 'Chaîne', 'Bracelet jonc'], typeAttr: ['Bague', 'Collier', 'Bracelet', 'Boucles d\'oreilles', 'Collier', 'Bracelet'], matiere: ['or 18 carats', 'argent 925', 'argent 925', 'or 18 carats', 'argent 925', 'plaqué or'], matAttr: ['Or', 'Argent', 'Argent', 'Or', 'Argent', 'Plaqué'], marque: ['Bijouterie locale', 'Pandora', 'Agatha', 'Bijouterie locale', 'Sans marque', 'Cleor'], detail: ['avec petit saphir', 'maille forçat', 'avec breloques', 'créoles', 'maille gourmette', 'lisse'], taille: ['taille 54', '45 cm', '18 cm', 'diamètre 3 cm', '50 cm', 'ajustable'], origine: ['Offerte et jamais portée.', 'Portée quelques mois.', 'Achetée en boutique, facture disponible.'] },
    pair: { bijou: 'typeAttr', bijou2: 'matiere', bijou3: 'matAttr', bijou4: 'marque', bijou5: 'detail', bijou6: 'taille' },
    q: ['gold ring jewelry', 'silver necklace', 'charm bracelet', 'gold earrings', 'silver chain', 'bangle bracelet'], qByOpt: 'bijou', photos: [2, 3],
  }),

  // ---------------------------------------------------------------- Famille (40)
  V('puericulture', 5, {
    title: 'Poussette {marque} {modele} {couleur}',
    desc: 'Poussette {marque} {modele}, {couleur}, {type}. Achetée {achat}, utilisée pour un enfant. {detail} Housse de pluie et ombrelle incluses. Nettoyée, prête à servir.',
    price: [120, 520], cond: BON,
    attrs: { type_produit: 'Poussette', marque: '{marque}', couleur: '{Couleur}' },
    opts: { marque: ['Babyzen', 'Cybex', 'Bugaboo', 'Joie', 'Chicco'], modele: ['Yoyo2', 'Balios S', 'Bee 6', 'Versatrax', 'Trio'], couleur: ['noir', 'gris', 'bleu', 'beige'], type: ['compacte cabine', 'tout-terrain', 'citadine', 'trio avec cosy', 'canne légère'], achat: ['en 2024', 'en 2023', 'l\'an dernier'], detail: ['Pliage à une main, se glisse dans un placard.', 'Grandes roues, suspensions, panier XXL.', 'Hamac réversible, nacelle vendue en option.', 'Compatible siège auto, adaptateurs fournis.'] },
    pair: { marque: 'modele' },
    q: ['baby stroller', 'stroller pram park'], photos: [2, 4],
  }),
  V('puericulture', 4, {
    title: 'Siège auto {marque} {groupe} isofix',
    desc: 'Siège auto {marque} {modele}, {groupe}, isofix, {rotation}. Jamais accidenté (obligation légale : un siège accidenté ne doit plus servir), notice fournie, housse lavée. Date de fabrication {annee}.',
    price: [60, 260], cond: BON,
    attrs: { type_produit: 'Siège auto', marque: '{marque}', couleur: '{Couleur}' },
    opts: { marque: ['Cybex', 'Maxi-Cosi', 'Britax Römer', 'Joie'], modele: ['Sirona', 'Pearl 360', 'Dualfix', 'Spin 360'], groupe: ['0+/1 (0-18 kg)', '1 (9-18 kg)', '2/3 (15-36 kg)', 'i-Size 40-105 cm'], rotation: ['pivotant 360°', 'dos et face route', 'réhausseur avec dossier', 'pivotant'], annee: [2022, 2023, 2024], couleur: ['noir', 'gris', 'bleu'] },
    pair: { marque: 'modele', groupe: 'rotation' },
    q: ['child car seat', 'baby car seat isofix'], photos: [2, 3],
  }),
  V('puericulture', 3, {
    title: 'Chaise haute {marque} {modele}',
    desc: 'Chaise haute {marque} {modele}, {type}, {couleur}. Tablette amovible passe au lave-vaisselle, harnais 5 points, {detail}. Nettoyée en profondeur.',
    price: [35, 190], cond: BON,
    attrs: { type_produit: 'Chaise haute', marque: '{marque}', couleur: '{Couleur}' },
    opts: { marque: ['Stokke', 'Ikea', 'Chicco', 'Childhome'], modele: ['Tripp Trapp', 'Antilop', 'Polly', 'Evolu 2'], type: ['évolutive en bois', 'compacte', 'pliante réglable', 'évolutive'], couleur: ['blanc', 'beige', 'gris', 'marron'], detail: ['kit bébé et coussin inclus', 'plateau et coussin inclus', 'réglable en hauteur sur 6 positions', 'réglable en 3 hauteurs'] },
    pair: { marque: 'modele', marque2: 'type', marque3: 'detail' },
    q: ['high chair baby wooden', 'baby high chair kitchen'], photos: [2, 3],
  }),
  V('puericulture', 3, {
    title: 'Porte-bébé {marque} {modele}',
    desc: 'Porte-bébé {marque} {modele}, {position}, utilisable {age}. Sangles rembourrées, lavé en machine, sans usure. {detail}',
    price: [40, 130], cond: BON,
    attrs: { type_produit: 'Porte-bébé', marque: '{marque}', couleur: '{Couleur}' },
    opts: { marque: ['Ergobaby', 'BabyBjörn', 'Love Radius'], modele: ['Omni 360', 'Mini', 'Physiocarrier'], position: ['ventral, dorsal et hanche', 'ventral face à soi et face au monde', 'ventral et dorsal'], age: ['de la naissance à 20 kg', 'de la naissance à 11 kg', 'de 4 mois à 20 kg'], couleur: ['gris', 'noir', 'bleu', 'beige'], detail: ['Coussin nouveau-né inclus.', 'Idéal pour les premiers mois.', 'Support de tête amovible.'] },
    pair: { marque: 'modele', marque2: 'position', marque3: 'age', marque4: 'detail' },
    q: ['baby carrier parent', 'baby sling carrier'], photos: [2, 3],
  }),
  V('puericulture', 3, {
    title: 'Lot {lot} bébé, {etat}',
    desc: 'Lot {lot} : {contenu}. {etat2} Vendu ensemble, prix pour le lot. Non fumeur, sans animaux.',
    price: [20, 90], cond: BON,
    attrs: { type_produit: '{typeAttr}', marque: '{marque}' },
    opts: { lot: ['de matériel de repas', 'de bain et toilette', 'de jouets d\'éveil'], typeAttr: ['Repas / Biberons', 'Baignoire / Toilette', 'Jouet d\'éveil'], contenu: ['6 biberons Avent, stérilisateur micro-ondes, chauffe-biberon, cuillères', 'baignoire évolutive, transat de bain, thermomètre, cape de bain', 'tapis d\'éveil, arche, hochets, portique et 3 doudous'], marque: ['Philips Avent', 'Stokke', 'Fisher-Price'], etat: ['très bon état', 'bon état', 'très bon état'], etat2: ['Tout est complet et stérilisé.', 'Lavé et désinfecté.', 'Piles neuves fournies.'] },
    pair: { lot: 'typeAttr', lot2: 'contenu', lot3: 'marque', lot4: 'etat', lot5: 'etat2' },
    q: ['baby bottles set', 'baby bath tub', 'baby play mat toys'], qByOpt: 'lot', photos: [2, 3],
  }),
  V('mobilier-bebe', 5, {
    title: 'Lit bébé {marque} {dim} avec matelas',
    desc: 'Lit bébé {marque} {dim} cm en {matiere}, {couleur}, sommier réglable sur {niveaux} hauteurs, barreaux amovibles pour évoluer en lit enfant. Matelas {matelas} inclus, housse lavée. Démonté pour le transport, notice fournie.',
    price: [60, 260], cond: BON,
    attrs: { type_meuble: '{typeAttr}', marque: '{marque}', couleur: '{Couleur}' },
    opts: { marque: ['Ikea', 'Vertbaudet', 'Sauthon', 'Oeuf', 'Childhome'], dim: ['60 × 120', '70 × 140', '60 × 120'], typeAttr: ['Lit', 'Lit évolutif', 'Lit'], matiere: ['hêtre massif', 'bois laqué', 'pin'], couleur: ['blanc', 'beige', 'marron', 'gris'], niveaux: [2, 3], matelas: ['Tediber', 'Ikea', 'neuf sous plastique', 'en mousse'] },
    pair: { dim: 'typeAttr' },
    q: ['baby crib nursery', 'wooden cot bedroom'], photos: [2, 4],
  }),
  V('mobilier-bebe', 4, {
    title: 'Commode à langer {marque} {couleur}',
    desc: 'Commode {marque} avec plan à langer amovible, {couleur}, {tiroirs} tiroirs, {dim}. Solide, tiroirs coulissants, angles arrondis. Matelas à langer offert. À démonter sur place (je peux aider).',
    price: [70, 240], cond: BON,
    attrs: { type_meuble: 'Table à langer', marque: '{marque}', couleur: '{Couleur}' },
    opts: { marque: ['Ikea', 'Vertbaudet', 'Sauthon', 'Galipette'], couleur: ['blanc', 'gris', 'beige', 'marron'], tiroirs: [3, 4], dim: ['80 × 90 × 50 cm', '90 × 95 × 55 cm'] },
    q: ['changing table dresser nursery', 'nursery dresser'], photos: [2, 3],
  }),
  V('mobilier-bebe', 3, {
    title: '{meuble} chambre enfant {marque}',
    desc: '{meuble} {marque} pour chambre d\'enfant, {couleur}, {detail}. Aucun jeu, aucune rayure profonde. Se démonte facilement.',
    price: [30, 190], cond: BON,
    attrs: { type_meuble: '{typeAttr}', marque: '{marque}', couleur: '{Couleur}' },
    opts: { meuble: ['Armoire', 'Bureau et chaise', 'Parc en bois'], typeAttr: ['Armoire', 'Bureau / Chaise enfant', 'Parc'], marque: ['Ikea', 'Flexa', 'Geuther'], couleur: ['blanc', 'bois clair', 'gris'], detail: ['deux portes, penderie et trois étagères', 'plateau inclinable, chaise réglable', 'pliable, tapis de sol inclus'] },
    pair: { meuble: 'typeAttr', meuble2: 'marque', meuble3: 'detail' },
    q: ['kids wardrobe white', 'children desk chair', 'wooden playpen baby'], qByOpt: 'meuble', photos: [2, 3],
  }),
  V('vetements-bebe', 6, {
    title: 'Lot vêtements bébé {sexe} {taille}, {nb} pièces',
    desc: 'Lot de {nb} pièces taille {taille} pour {sexe} : {contenu}. Marques {marques}. Lavés, sans tache ni bouloche, non fumeur. Photos du lot complet sur demande.',
    price: [12, 45], cond: BON,
    attrs: { taille_bebe: '{taille}', type_vetement: 'Lot de vêtements', sexe: '{sexeAttr}', marque: 'Divers' },
    opts: { sexe: ['fille', 'garçon', 'mixte'], sexeAttr: ['Fille', 'Garçon', 'Mixte'], taille: ['3 mois', '6 mois', '9 mois', '12 mois', '18 mois'], nb: [12, 15, 20, 25], contenu: ['bodies, pyjamas, gigoteuse, bonnets', 'pantalons, gilets, t-shirts, chaussettes', 'ensembles, salopettes, pulls'], marques: ['Petit Bateau, Vertbaudet, H&M', 'Kiabi, Okaïdi, Tape à l\'œil', 'Jacadi, Bout\'chou, Zara Baby'] },
    pair: { sexe: 'sexeAttr' },
    q: ['baby clothes folded', 'newborn clothes lot'], photos: [2, 3],
  }),
  V('vetements-bebe', 4, {
    title: '{type} bébé {marque} {taille}, {saison}',
    desc: '{type} {marque} taille {taille}, {couleur}, {saison}. Porté {porte}, comme neuf. {detail}',
    price: [8, 45], cond: ['tres_bon_etat', 'neuf'],
    attrs: { taille_bebe: '{taille}', type_vetement: '{typeAttr}', sexe: 'Mixte', marque: '{marque}' },
    opts: { type: ['Combinaison pilote', 'Manteau', 'Pyjama en velours (lot de 3)', 'Chaussons en cuir'], typeAttr: ['Manteau / Combinaison', 'Manteau / Combinaison', 'Pyjama', 'Chaussures'], marque: ['Petit Bateau', 'Jacadi', 'Petit Bateau', 'Bobux'], taille: ['6 mois', '12 mois', '18 mois', '9 mois'], couleur: ['bleu marine', 'gris chiné', 'rayé', 'marron'], saison: ['hiver', 'mi-saison', 'toutes saisons', 'premiers pas'], porte: ['un hiver', 'quelques fois', 'un mois', 'deux mois'], detail: ['Doublure polaire.', 'Capuche et boutons pression.', 'Fermetures pression, coton bio.', 'Semelle souple antidérapante.'] },
    pair: { type: 'typeAttr', type2: 'marque', type3: 'saison', type4: 'detail' },
    q: ['baby snowsuit', 'baby coat', 'baby pajamas', 'baby leather shoes'], qByOpt: 'type', photos: [2, 3],
  }),

  // ---------------------------------------------------------------- Animaux (20) — accessoires uniquement (aucune vente d'animal)
  V('accessoires-animaux', 5, {
    title: 'Aquarium {litres} L complet avec meuble',
    desc: 'Aquarium {marque} de {litres} litres avec meuble assorti, filtre {filtre}, chauffage, éclairage LED, décor et gravier. Utilisé {duree}, aucune fuite, vitres sans rayure. Vidé et nettoyé, à transporter à deux.',
    price: [80, 420], cond: BON,
    attrs: { animal: 'Poisson / Aquarium', type_accessoire: 'Aquarium / Terrarium', marque: '{marque}' },
    opts: { marque: ['Juwel', 'Eheim', 'Aquatlantis', 'Tetra'], litres: [60, 120, 180, 240], filtre: ['interne', 'externe', 'interne Bioflow'], duree: ['deux ans', 'trois ans', 'un an'] },
    q: ['aquarium fish tank living room', 'planted aquarium'], photos: [2, 4],
  }),
  V('accessoires-animaux', 5, {
    title: 'Cage {animal} {marque} {dim}, avec accessoires',
    desc: 'Cage {marque} pour {animal}, {dim}, avec {accessoires}. Barreaux et bac en parfait état, désinfectée. Notre compagnon a déménagé dans un enclos plus grand.',
    price: [30, 140], cond: BON,
    attrs: { animal: '{animalAttr}', type_accessoire: 'Cage / Niche / Enclos', marque: '{marque}' },
    opts: { animal: ['lapin', 'cochon d\'Inde', 'hamster', 'perruches', 'chinchilla'], animalAttr: ['Rongeur', 'Rongeur', 'Rongeur', 'Oiseau', 'Rongeur'], marque: ['Ferplast', 'Zolux', 'Savic', 'Vadigran', 'Ferplast'], dim: ['120 × 60 cm', '100 × 50 cm', '80 × 50 cm', '90 × 60 cm, 3 étages', '100 × 60 cm'], accessoires: ['abreuvoir, mangeoire, maison en bois', 'râtelier, abreuvoir, litière restante', 'roue silencieuse, tunnels, biberon', 'perchoirs, mangeoires, balançoire', 'plateformes, bac à bain, biberon'] },
    pair: { animal: 'animalAttr', animal2: 'marque', animal3: 'dim', animal4: 'accessoires' },
    q: ['rabbit cage', 'guinea pig cage', 'hamster cage', 'bird cage parakeet', 'chinchilla cage'], qByOpt: 'animal', photos: [2, 3],
  }),
  V('accessoires-animaux', 5, {
    title: '{article} chien {marque} {taille}',
    desc: '{article} pour chien {marque}, taille {taille} ({poids}), {couleur}. {detail} Lavé, sans odeur, sans usure. Notre chien a changé de gabarit.',
    price: [15, 120], cond: BON,
    attrs: { animal: 'Chien', type_accessoire: '{typeAttr}', marque: '{marque}' },
    opts: { article: ['Panier orthopédique', 'Caisse de transport', 'Harnais et laisse', 'Manteau imperméable', 'Niche en bois'], typeAttr: ['Autre', 'Transport', 'Autre', 'Autre', 'Cage / Niche / Enclos'], marque: ['Trixie', 'Petmate', 'Julius-K9', 'Hurtta', 'Kerbl'], taille: ['L', 'M', 'M', 'S', 'XL'], poids: ['25-40 kg', '10-20 kg', '15-25 kg', '5-10 kg', 'grands chiens'], couleur: ['gris', 'beige', 'noir', 'orange', 'bois naturel'], detail: ['Mousse à mémoire de forme, housse déhoussable.', 'Homologuée IATA, porte métallique.', 'Poignée dorsale, laisse 2 m incluse.', 'Doublure polaire, bandes réfléchissantes.', 'Toit ouvrant, pieds surélevés.'] },
    pair: { article: 'typeAttr', article2: 'marque', article3: 'taille', article4: 'poids', article5: 'couleur', article6: 'detail' },
    q: ['dog bed', 'dog crate transport', 'dog harness leash', 'dog raincoat', 'wooden dog house'], qByOpt: 'article', photos: [2, 3],
  }),
  V('accessoires-animaux', 5, {
    title: '{article} chat {marque}',
    desc: '{article} pour chat {marque}, {detail}. {etat} Notre chat n\'en veut plus, tant pis pour lui.',
    price: [10, 150], cond: BON,
    attrs: { animal: 'Chat', type_accessoire: '{typeAttr}', marque: '{marque}' },
    opts: { article: ['Arbre à chat', 'Fontaine à eau', 'Litière autonettoyante', 'Sac de transport', 'Chatière connectée'], typeAttr: ['Jouet', 'Alimentation', 'Toilettage / Soins', 'Transport', 'Autre'], marque: ['Trixie', 'Catit', 'PetKit', 'Sherpa', 'SureFlap'], detail: ['1,50 m, trois plateformes et niche, sisal intact', '2 L, filtre neuf, silencieuse', 'tapis et bac fournis, fonctionne parfaitement', 'homologué cabine, pliable', 'lecture de la puce, notice fournie'], etat: ['Très bon état.', 'Nettoyée et détartrée.', 'Filtres neufs inclus.', 'Comme neuf.', 'Installée un an.'] },
    pair: { article: 'typeAttr', article2: 'marque', article3: 'detail', article4: 'etat' },
    q: ['cat tree scratching post', 'cat water fountain', 'automatic litter box', 'cat carrier bag', 'cat flap door'], qByOpt: 'article', photos: [2, 3],
  }),
];
