// Archétypes d'annonces (AUDIT §71) — véhicules, immobilier, emploi, matériel pro, vacances, services.
// Chaque archétype produit `n` annonces ; les {tokens} sont tirés dans `opts` (déterministe) ; `q` = requête photo (anglais).
const V = (slug, n, def) => ({ slug, n, ...def });
const BON = ['bon_etat', 'tres_bon_etat'];

module.exports = [
  // ---------------------------------------------------------------- Véhicules (90)
  V('voitures', 6, {
    title: 'Peugeot 208 {version} {annee}, {km} km',
    desc: 'Peugeot 208 {version} de {annee}, {km} km, carnet d\'entretien à jour et contrôle technique de moins de six mois. Véhicule non fumeur, intérieur propre, deux clés. {ct} Vendue avec ses quatre pneus en bon état.',
    price: [7900, 14500], cond: BON,
    attrs: { marque: 'Peugeot', modele: '208', annee: '{annee}', kilometrage: '{km}', carburant: '{carb}', boite: '{boite}', type_vehicule: 'Citadine', portes: '5', couleur: '{Couleur}', controle_technique: true },
    opts: { version: ['1.2 PureTech 75', '1.2 PureTech 100', '1.5 BlueHDi 100', 'Allure', 'Active'], annee: [2017, 2018, 2019, 2020, 2021], km: [42000, 58000, 71000, 89000, 103000, 118000], carb: ['Essence', 'Essence', 'Diesel'], boite: ['Manuelle', 'Manuelle', 'Automatique'], couleur: ['gris', 'blanc', 'noir', 'bleu', 'rouge'], ct: ['Aucun frais à prévoir.', 'Distribution faite à 60 000 km.', 'Révision complète effectuée en mai.'] },
    q: ['Peugeot 208 car', 'small hatchback car street'], qFirst: true, photos: [3, 5],
  }),
  V('voitures', 6, {
    title: 'Renault Clio {gen} {version}, {annee}',
    desc: 'Clio {gen} {version}, {km} km au compteur, {annee}. Entretien suivi en concession, pneus et plaquettes récents. Climatisation, régulateur, Bluetooth. {ct}',
    price: [6500, 15900], cond: BON,
    attrs: { marque: 'Renault', modele: 'Clio', annee: '{annee}', kilometrage: '{km}', carburant: '{carb}', boite: 'Manuelle', type_vehicule: 'Citadine', portes: '5', couleur: '{Couleur}', controle_technique: true, premiere_main: '{main}' },
    opts: { gen: ['IV', 'IV', 'V'], version: ['TCe 90', 'dCi 90', 'TCe 100', 'Intens', 'Zen'], annee: [2016, 2018, 2019, 2020, 2021, 2022], km: [38000, 54000, 67000, 82000, 96000, 124000], carb: ['Essence', 'Diesel'], couleur: ['gris', 'blanc', 'noir', 'rouge', 'bleu'], main: [true, false], ct: ['Contrôle technique vierge de ce mois-ci.', 'Jamais accidentée, carrosserie sans choc.', 'Première main, factures disponibles.'] },
    q: ['Renault Clio car', 'compact car parked'], photos: [3, 5],
  }),
  V('voitures', 5, {
    title: 'Renault Captur {version} {annee}, {km} km',
    desc: 'Renault Captur {version}, {annee}, {km} km. Position de conduite surélevée, coffre modulable, caméra de recul, Apple CarPlay. Toujours garée au garage. {ct}',
    price: [7200, 13900], cond: BON,
    attrs: { marque: 'Renault', modele: 'Captur', annee: '{annee}', kilometrage: '{km}', carburant: '{carb}', boite: '{boite}', type_vehicule: '4x4 / SUV / Crossover', portes: '5', couleur: '{Couleur}', controle_technique: true },
    opts: { version: ['TCe 90 Zen', 'TCe 130 Intens', 'dCi 95 Business'], annee: [2017, 2018, 2019, 2020, 2021], km: [45000, 61000, 78000, 95000, 112000], carb: ['Essence', 'Essence', 'Diesel'], boite: ['Manuelle', 'Automatique'], couleur: ['blanc', 'gris', 'bleu', 'rouge'], ct: ['Pneus neufs à l\'avant.', 'Batterie remplacée en 2025.', 'Carnet complet.'] },
    q: ['Renault Captur'], photos: [3, 4], // Citroën C3 abandonnée : Pexels n'a que des Citroën anciennes, le Captur y est très bien couvert
  }),
  V('voitures', 5, {
    title: 'Volkswagen {modele} {version} {annee}',
    desc: 'Volkswagen {modele} {version} de {annee}, {km} km, entretien en concession. Boîte {boite}, {carb}, GPS, jantes alu, sièges chauffants. {ct}',
    price: [11900, 24500], cond: BON,
    attrs: { marque: 'Volkswagen', modele: '{modele}', annee: '{annee}', kilometrage: '{km}', carburant: '{carb}', boite: '{boite}', type_vehicule: '{type}', portes: '5', couleur: '{Couleur}', controle_technique: true },
    opts: { modele: ['Golf', 'Polo', 'T-Roc', 'Tiguan'], version: ['1.0 TSI 95', '1.5 TSI 130', '2.0 TDI 150', '1.6 TDI 115'], annee: [2017, 2018, 2019, 2020, 2021, 2022], km: [52000, 68000, 84000, 99000, 127000], carb: ['Essence', 'Diesel'], boite: ['Manuelle', 'Automatique', 'Automatique'], type: ['Berline', 'Citadine', '4x4 / SUV / Crossover'], couleur: ['gris', 'noir', 'blanc', 'bleu'], ct: ['Contrôle technique OK.', 'Deux pneus neufs.', 'Vendu avec jeu de pneus hiver.'] },
    q: ['Volkswagen Golf car', 'Volkswagen Polo car', 'Volkswagen T-Roc SUV', 'Volkswagen Tiguan'], qByOpt: 'modele', qFallback: ['Volkswagen car parked'], photos: [3, 5],
  }),
  V('voitures', 4, {
    title: 'Toyota Yaris Hybride {annee}, {km} km',
    desc: 'Yaris hybride {version}, {annee}, {km} km. Consommation réelle autour de 4 L/100 en ville, boîte automatique, caméra de recul. Entretien Toyota. {ct}',
    price: [12900, 19900], cond: ['tres_bon_etat', 'bon_etat'],
    attrs: { marque: 'Toyota', modele: 'Yaris', annee: '{annee}', kilometrage: '{km}', carburant: 'Hybride', boite: 'Automatique', type_vehicule: 'Citadine', portes: '5', couleur: '{Couleur}', critair: '1', controle_technique: true },
    opts: { version: ['Dynamic', 'Design', 'Collection', 'France'], annee: [2019, 2020, 2021, 2022], km: [31000, 47000, 63000, 78000], couleur: ['blanc', 'gris', 'rouge', 'bleu'], ct: ['Garantie constructeur hybride restante.', 'Pneus été neufs.', 'Première main.'] },
    q: ['Toyota Yaris hybrid', 'red hatchback car'], photos: [3, 4],
  }),
  V('voitures', 4, {
    title: 'Dacia {modele} {version}, {annee}',
    desc: 'Dacia {modele} {version} de {annee}, {km} km, première main. Voiture simple et fiable, entretien régulier, aucun voyant. Idéale pour un premier véhicule ou les trajets quotidiens. {ct}',
    price: [6900, 15500], cond: BON,
    attrs: { marque: 'Dacia', modele: '{modele}', annee: '{annee}', kilometrage: '{km}', carburant: '{carb}', boite: 'Manuelle', type_vehicule: '{type}', portes: '5', couleur: '{Couleur}', controle_technique: true, premiere_main: true },
    opts: { modele: ['Sandero', 'Duster', 'Duster'], version: ['Stepway TCe 90', '1.5 dCi 115', 'SCe 65 Essential', 'Prestige'], annee: [2017, 2019, 2020, 2021, 2022], km: [39000, 55000, 72000, 90000, 108000], carb: ['Essence', 'Diesel', 'GPL'], type: ['Citadine', '4x4 / SUV / Crossover', 'Berline'], couleur: ['blanc', 'gris', 'bleu', 'marron'], ct: ['Crochet d\'attelage.', 'Barres de toit fournies.', 'Contrôle technique du mois dernier.'] },
    q: ['Dacia Sandero Stepway', 'Dacia Duster', 'Dacia Duster'], qByOpt: 'modele', photos: [3, 4], // pas de Logan sur Pexels : modèle retiré
  }),
  V('voitures', 4, {
    title: '{marque} {modele} {annee}, {km} km, {carb}',
    desc: '{marque} {modele} {annee}, {km} km, {carb}, boîte {boite}. Véhicule bien entretenu, factures à l\'appui, deux clés, contrôle technique récent. {ct}',
    price: [9900, 22900], cond: BON,
    attrs: { marque: '{marque}', modele: '{modele}', annee: '{annee}', kilometrage: '{km}', carburant: '{carb}', boite: '{boite}', portes: '5', couleur: '{Couleur}', controle_technique: true },
    opts: { marque: ['Ford', 'Opel', 'Skoda', 'Seat', 'Hyundai', 'Kia'], modele: ['Focus', 'Corsa', 'Octavia', 'Ibiza', 'i20', 'Ceed'], annee: [2016, 2018, 2019, 2020, 2021], km: [58000, 74000, 91000, 105000, 133000], carb: ['Essence', 'Diesel'], boite: ['Manuelle', 'Automatique'], couleur: ['gris', 'noir', 'blanc', 'bleu', 'rouge'], ct: ['Pneus quatre saisons récents.', 'Vidange faite il y a 2 000 km.', 'Jamais de sinistre.'] },
    pair: { marque: 'modele' },
    q: ['Ford Focus car', 'Opel Corsa car', 'Skoda Octavia', 'Seat Ibiza', 'Hyundai i20', 'Kia Ceed'], qByOpt: 'marque', photos: [3, 4],
  }),
  V('voitures', 3, {
    title: 'BMW {modele} {version} {annee}',
    desc: 'BMW {modele} {version}, {annee}, {km} km. Entretien BMW, pack M, cuir, GPS professionnel, boîte automatique. Carrosserie et jantes sans défaut. {ct}',
    price: [16900, 31900], cond: ['tres_bon_etat', 'bon_etat'],
    attrs: { marque: 'BMW', modele: '{modele}', annee: '{annee}', kilometrage: '{km}', carburant: '{carb}', boite: 'Automatique', type_vehicule: '{type}', portes: '5', couleur: '{Couleur}', sellerie: 'Cuir', controle_technique: true },
    opts: { modele: ['Série 1', 'Série 3', 'X1'], version: ['118d', '320d', 'sDrive18d', '118i'], annee: [2017, 2018, 2019, 2020], km: [61000, 78000, 94000, 121000], carb: ['Diesel', 'Essence'], type: ['Berline', '4x4 / SUV / Crossover'], couleur: ['noir', 'gris', 'blanc', 'bleu'], ct: ['Garantie 12 mois possible via un garage partenaire.', 'Pneus Michelin récents.', 'Deux jeux de jantes.'] },
    q: ['BMW 1 series hatchback', 'BMW 3 series car', 'BMW X1 SUV'], qByOpt: 'modele', qFallback: ['BMW car parked street'], photos: [3, 5],
  }),
  V('voitures', 3, {
    title: 'Tesla Model 3 {version} {annee}',
    desc: 'Tesla Model 3 {version}, {annee}, {km} km, autopilot standard, batterie à {sante} % de capacité. Chargeur mobile et câble type 2 inclus, jantes Aero. Recharge gratuite Supercharger non transférable.',
    price: [24900, 33900], cond: ['tres_bon_etat', 'bon_etat'],
    attrs: { marque: 'Tesla', modele: 'Model 3', annee: '{annee}', kilometrage: '{km}', carburant: 'Électrique', boite: 'Automatique', type_vehicule: 'Berline', portes: '4', couleur: '{Couleur}', critair: '0 (électrique)', controle_technique: true },
    opts: { version: ['Standard Plus', 'Grande Autonomie', 'Propulsion'], annee: [2020, 2021, 2022, 2023], km: [28000, 41000, 56000, 72000], sante: [91, 93, 95, 96], couleur: ['blanc', 'noir', 'gris', 'bleu'] },
    q: ['Tesla Model 3', 'electric car charging'], photos: [3, 5],
  }),
  V('voitures', 3, {
    title: 'Fiat 500 {version} {annee}, faible kilométrage',
    desc: 'Fiat 500 {version} de {annee}, seulement {km} km. Toit panoramique, jantes alu, parfaite pour la ville. Entretien suivi, aucun frais à prévoir. {ct}',
    price: [7900, 12900], cond: ['tres_bon_etat', 'bon_etat'],
    attrs: { marque: 'Fiat', modele: '500', annee: '{annee}', kilometrage: '{km}', carburant: '{carb}', boite: 'Manuelle', type_vehicule: 'Citadine', portes: '3', couleur: '{Couleur}', controle_technique: true },
    opts: { version: ['1.2 Lounge', '1.0 Hybrid Dolcevita', '1.2 Pop'], annee: [2018, 2019, 2020, 2021, 2022], km: [24000, 33000, 41000, 52000], carb: ['Essence', 'Hybride'], couleur: ['blanc', 'rouge', 'vert', 'beige', 'bleu'], ct: ['Toujours garée en box.', 'Contrôle technique vierge.', 'Sièges impeccables.'] },
    q: ['Fiat 500 car', 'small red car city'], photos: [3, 4],
  }),
  V('voitures', 3, {
    title: '{marque} {modele} {annee} monospace 7 places',
    desc: '{marque} {modele} 7 places, {annee}, {km} km, {carb}. Parfait pour une famille : sièges indépendants, grand coffre, attelage. Entretien à jour, contrôle technique OK. {ct}',
    price: [10900, 21900], cond: BON,
    attrs: { marque: '{marque}', modele: '{modele}', annee: '{annee}', kilometrage: '{km}', carburant: '{carb}', boite: '{boite}', type_vehicule: 'Monospace', portes: '5', places: 7, couleur: '{Couleur}', controle_technique: true },
    opts: { marque: ['Renault', 'Citroën', 'Peugeot'], modele: ['Grand Scénic', 'C4 Picasso', '5008'], annee: [2017, 2018, 2019, 2020], km: [78000, 96000, 115000, 138000], carb: ['Diesel', 'Diesel', 'Essence'], boite: ['Manuelle', 'Automatique'], couleur: ['gris', 'noir', 'blanc', 'bleu'], ct: ['Distribution faite.', 'Pneus neufs.', 'Sièges enfant possibles en sus.'] },
    pair: { marque: 'modele' },
    q: ['Renault Scenic', 'Citroën C4 Picasso', 'Peugeot 5008'], qByOpt: 'marque', qFallback: ['family minivan car'], photos: [3, 4],
  }),
  V('voitures', 2, {
    title: 'Mini Cooper {annee}, {km} km, toit noir',
    desc: 'Mini Cooper 3 portes, {annee}, {km} km, boîte {boite}. Pack Chili, toit et rétroviseurs noirs, jantes 17 pouces, entretien Mini. Voiture très amusante et économique.',
    price: [12900, 18900], cond: ['tres_bon_etat', 'bon_etat'],
    attrs: { marque: 'Mini', modele: 'Mini 3 portes', annee: '{annee}', kilometrage: '{km}', carburant: 'Essence', boite: '{boite}', type_vehicule: 'Citadine', portes: '3', couleur: '{Couleur}', controle_technique: true },
    opts: { annee: [2017, 2018, 2019, 2020], km: [44000, 57000, 69000, 83000], boite: ['Manuelle', 'Automatique'], couleur: ['rouge', 'vert', 'bleu', 'blanc'] },
    q: ['Mini Cooper car'], photos: [3, 4],
  }),
  V('voitures', 2, {
    title: 'Audi A3 Sportback {version} {annee}',
    desc: 'Audi A3 Sportback {version}, {annee}, {km} km, S line, boîte S tronic, virtual cockpit. Entretien Audi, pneus récents, aucun frais à prévoir. {ct}',
    price: [17900, 26900], cond: ['tres_bon_etat', 'bon_etat'],
    attrs: { marque: 'Audi', modele: 'A3', annee: '{annee}', kilometrage: '{km}', carburant: '{carb}', boite: 'Automatique', type_vehicule: 'Berline', portes: '5', couleur: '{Couleur}', controle_technique: true },
    opts: { version: ['35 TFSI', '30 TDI', '35 TDI'], annee: [2018, 2019, 2020, 2021], km: [49000, 66000, 81000, 97000], carb: ['Essence', 'Diesel'], couleur: ['gris', 'noir', 'blanc'], ct: ['Garantie constructeur jusqu\'à fin 2026.', 'Première main.', 'Carnet complet.'] },
    q: ['Audi A3 car'], photos: [3, 4],
  }),
  V('motos', 4, {
    title: 'Yamaha {modele} {annee}, {km} km',
    desc: 'Yamaha {modele} de {annee}, {km} km, {perm}. Révision faite, pneus à 70 %, chaîne et kit neufs. Vendue avec top-case et protège-mains. Jamais tombée.',
    price: [4900, 8900], cond: BON,
    attrs: { marque: 'Yamaha', modele: '{modele}', annee: '{annee}', kilometrage: '{km}', cylindree: '{cyl}', type_moto: 'Roadster', permis: '{permis}', couleur: '{Couleur}' },
    opts: { modele: ['MT-07', 'MT-09', 'MT-03'], annee: [2018, 2019, 2020, 2021, 2022], km: [8500, 14000, 21000, 27000, 34000], cyl: [689, 847, 321], perm: ['bridée A2 possible', 'full', 'A2'], permis: ['A2', 'A', 'A2'], couleur: ['bleu', 'noir', 'gris'] },
    pair: { modele: 'cyl' },
    q: ['Yamaha MT-07 motorcycle', 'Yamaha MT-09 motorcycle', 'Yamaha MT-03 motorcycle'], qByOpt: 'modele', qFallback: ['Yamaha naked motorcycle'], photos: [3, 4],
  }),
  V('motos', 3, {
    title: 'Honda {modele} {annee}',
    desc: 'Honda {modele}, {annee}, {km} km, entretien concession. Moto fiable et facile, idéale pour débuter ou pour les trajets quotidiens. Deux clés, manuel, pneus récents.',
    price: [3900, 7400], cond: BON,
    attrs: { marque: 'Honda', modele: '{modele}', annee: '{annee}', kilometrage: '{km}', cylindree: '{cyl}', type_moto: '{type}', permis: '{permis}', couleur: '{Couleur}' },
    opts: { modele: ['CB 500 F', 'CB 125 R', 'CB 650 R'], annee: [2018, 2019, 2020, 2021], km: [6500, 12000, 18500, 25000], cyl: [471, 125, 649], type: ['Roadster', '125', 'Roadster'], permis: ['A2', 'A1', 'A'], couleur: ['rouge', 'noir', 'gris'] },
    pair: { modele: 'cyl', modele2: 'type' },
    q: ['Honda motorcycle', 'motorcycle parked'], photos: [3, 4],
  }),
  V('motos', 3, {
    title: 'Scooter {marque} {modele} 125, {annee}',
    desc: 'Scooter 125 {marque} {modele}, {annee}, {km} km, révisé, pneus neufs. Coffre sous la selle pour un casque, pare-brise, top-case. Accessible avec le permis B après formation 7 h.',
    price: [1900, 3900], cond: BON,
    attrs: { marque: '{marque}', modele: '{modele}', annee: '{annee}', kilometrage: '{km}', cylindree: 125, type_moto: 'Scooter', permis: 'B', couleur: '{Couleur}' },
    opts: { marque: ['Yamaha', 'Piaggio', 'Vespa'], modele: ['NMAX', 'Medley', 'Primavera'], annee: [2019, 2020, 2021, 2022], km: [5200, 9800, 14300, 19000], couleur: ['blanc', 'gris', 'noir', 'bleu'] },
    pair: { marque: 'modele' },
    q: ['Yamaha NMAX scooter', 'Piaggio Medley scooter', 'Vespa scooter parked'], qByOpt: 'marque', qFallback: ['scooter 125 city'], photos: [2, 4],
  }),
  V('motos', 3, {
    title: '{marque} {modele} trail {annee}, {km} km',
    desc: '{marque} {modele}, trail routier de {annee}, {km} km. Valises latérales, bulle haute, poignées chauffantes, protection moteur. Entretien suivi, prête pour le voyage.',
    price: [6900, 12900], cond: BON,
    attrs: { marque: '{marque}', modele: '{modele}', annee: '{annee}', kilometrage: '{km}', cylindree: '{cyl}', type_moto: 'Trail', permis: 'A', couleur: '{Couleur}' },
    opts: { marque: ['BMW', 'Kawasaki', 'Suzuki'], modele: ['F 750 GS', 'Versys 650', 'DL 650 V-Strom'], annee: [2017, 2018, 2019, 2020, 2021], km: [19000, 27000, 36000, 44000], cyl: [853, 649, 645], couleur: ['blanc', 'vert', 'jaune', 'noir'] },
    pair: { marque: 'modele', modele: 'cyl' },
    q: ['BMW GS motorcycle', 'Kawasaki Versys motorcycle', 'Suzuki V-Strom motorcycle'], qByOpt: 'marque', qFallback: ['adventure motorcycle touring'], photos: [3, 4],
  }),
  V('motos', 2, {
    title: 'Triumph {modele} {annee}',
    desc: 'Triumph {modele}, {annee}, {km} km, échappement d\'origine conservé. Moto néo-rétro très saine, jamais tombée, révisée au printemps. Vendue avec housse et batterie neuve.',
    price: [7400, 11900], cond: ['tres_bon_etat', 'bon_etat'],
    attrs: { marque: 'Triumph', modele: '{modele}', annee: '{annee}', kilometrage: '{km}', cylindree: 900, type_moto: 'Roadster', permis: 'A', couleur: '{Couleur}' },
    opts: { modele: ['Speed Twin', 'Bonneville', 'Scrambler'], annee: [2017, 2018, 2019, 2020], km: [12000, 17500, 23000, 31000], couleur: ['noir', 'vert', 'rouge'] },
    q: ['Triumph Bonneville motorcycle'], photos: [3, 4],
  }),
  V('utilitaires', 4, {
    title: '{marque} {modele} {version} {annee}, {km} km',
    desc: '{marque} {modele} {version} de {annee}, {km} km, {carb}. Utilitaire d\'artisan bien entretenu, cloison de séparation, attelage, révision récente. Vendu TTC, pas de TVA récupérable.',
    price: [8900, 19900], cond: BON,
    attrs: { marque: '{marque}', modele: '{modele}', annee: '{annee}', kilometrage: '{km}', carburant: '{carb}', boite: 'Manuelle', ptac: '{ptac}' },
    opts: { marque: ['Renault', 'Peugeot', 'Citroën', 'Fiat'], modele: ['Trafic', 'Expert', 'Jumpy', 'Ducato'], version: ['L1H1 dCi 120', 'L2H1 BlueHDi 120', 'Fourgon 2.0 HDi', 'L2H2 2.3 MultiJet'], annee: [2016, 2017, 2018, 2019, 2020], km: [98000, 124000, 143000, 167000, 189000], carb: ['Diesel'], ptac: [2800, 3000, 3100, 3500] },
    pair: { marque: 'modele' },
    q: ['Renault Trafic van', 'white cargo van', 'white cargo van', 'white cargo van'], qByOpt: 'marque', photos: [3, 4], // Pexels : Peugeot/Citroën anciens et aucun Ducato → fourgon blanc générique
  }),
  V('utilitaires', 4, {
    title: '{marque} {modele} {annee}, fourgonnette',
    desc: '{marque} {modele} {annee}, {km} km, petite fourgonnette pratique pour les livraisons ou le bricolage. Deux places, plancher bois, galerie de toit. Contrôle technique à jour.',
    price: [5900, 12900], cond: BON,
    attrs: { marque: '{marque}', modele: '{modele}', annee: '{annee}', kilometrage: '{km}', carburant: 'Diesel', boite: 'Manuelle', ptac: 2000 },
    opts: { marque: ['Renault', 'Citroën', 'Peugeot', 'Volkswagen'], modele: ['Kangoo', 'Berlingo', 'Partner', 'Caddy'], annee: [2015, 2017, 2018, 2019, 2020], km: [87000, 112000, 136000, 158000] },
    pair: { marque: 'modele' },
    q: ['Renault Kangoo van', 'white delivery van', 'white delivery van', 'white delivery van'], qByOpt: 'marque', qFallback: ['small delivery van'], photos: [2, 4], // Pexels : Caddy = combis anciens, Berlingo absent
  }),
  V('caravaning', 4, {
    title: 'Camping-car {marque} {annee}, {couchages} couchages',
    desc: 'Camping-car {marque} profilé de {annee}, {km} km, {couchages} couchages, moteur Fiat Ducato 2.3. Panneau solaire, store, porte-vélos, chauffage Truma. Contrôle technique OK, prêt à partir.',
    price: [29900, 54900], cond: BON,
    attrs: { type_caravaning: 'Camping-car', marque: '{marque}', annee: '{annee}', kilometrage: '{km}', couchages: '{couchages}' },
    opts: { marque: ['Chausson', 'Challenger', 'Pilote', 'Rapido', 'Bürstner'], annee: [2013, 2015, 2017, 2018, 2019], km: [48000, 67000, 82000, 96000], couchages: [2, 3, 4, 4] },
    q: ['motorhome camper van', 'campervan road trip'], photos: [3, 5],
  }),
  V('caravaning', 3, {
    title: 'Caravane {marque} {couchages} places, {annee}',
    desc: 'Caravane {marque} de {annee}, {couchages} couchages, PTAC {ptac} kg, auvent complet, cassette WC, chauffage. Stationnée sous abri, aucune infiltration. Idéale pour les vacances en famille.',
    price: [4900, 12900], cond: BON,
    attrs: { type_caravaning: 'Caravane', marque: '{marque}', annee: '{annee}', couchages: '{couchages}' },
    opts: { marque: ['Caravelair', 'Sterckeman', 'Fendt', 'Adria'], annee: [2010, 2014, 2016, 2018, 2020], couchages: [3, 4, 5], ptac: [1000, 1200, 1300, 1500] },
    q: ['travel trailer caravan', 'caravan camping'], photos: [2, 4],
  }),
  V('nautisme', 3, {
    title: '{type} {marque} {longueur} m, {annee}',
    desc: '{type} {marque} de {longueur} m, {annee}, moteur {moteur}, remorque incluse. Coque saine, électronique récente (sondeur, VHF), gilets et ancre fournis. Visible au port sur rendez-vous.',
    price: [6900, 24900], cond: BON,
    attrs: { type_bateau: '{typeAttr}', longueur: '{longueur}', annee: '{annee}' },
    opts: { type: ['Semi-rigide', 'Bateau à moteur', 'Voilier'], typeAttr: ['Semi-rigide', 'Bateau à moteur', 'Voilier'], marque: ['Zodiac', 'Jeanneau', 'Bénéteau', 'Quicksilver'], longueur: [4.5, 5.5, 6.2, 7], annee: [2008, 2012, 2016, 2019], moteur: ['Yamaha 60 ch', 'Mercury 115 ch', 'Suzuki 40 ch', 'inboard diesel 20 ch'] },
    pair: { type: 'typeAttr' },
    q: ['rigid inflatable boat', 'motor boat harbor', 'sailboat marina'], qByOpt: 'type', photos: [3, 4],
  }),
  V('nautisme', 2, {
    title: 'Kayak {type} {places} place{s}',
    desc: 'Kayak {type} {places} place{s}, {marque}, utilisé une dizaine de sorties en mer et en rivière. Vendu avec pagaie{s2}, gilet{s2} et sac de transport. Aucune fuite, aucune réparation.',
    price: [250, 690], cond: ['tres_bon_etat', 'bon_etat'],
    attrs: { type_bateau: 'Kayak / Paddle', longueur: '{longueur}', annee: '{annee}' },
    opts: { type: ['gonflable', 'rigide sit-on-top'], places: [1, 2], s: ['', 's'], s2: ['', 's'], marque: ['Itiwit', 'Sevylor', 'Tahe'], longueur: [3.2, 3.8, 4.1], annee: [2021, 2022, 2023] },
    pair: { places: 's', places2: 's2' },
    q: ['inflatable kayak', 'kayak lake'], qByOpt: 'type', photos: [2, 3],
  }),
  V('pieces-auto', 4, {
    title: '4 jantes alu {pouces}" {marque} avec pneus {saison}',
    desc: 'Lot de quatre jantes alu {pouces} pouces d\'origine {marque}, montées avec pneus {saison} {dim} à {usure} % d\'usure. Aucune voile, léger frottement sur une jante. Démontées pour passage en jantes plus grandes.',
    price: [280, 690], cond: BON,
    attrs: { type_piece: 'Pneus / Jantes', compatibilite: '{marque} — entraxe {entraxe}' },
    opts: { pouces: [16, 17, 18], marque: ['Peugeot', 'Volkswagen', 'BMW', 'Renault', 'Audi'], saison: ['hiver', 'été', 'quatre saisons'], dim: ['205/55 R16', '225/45 R17', '225/40 R18'], usure: [30, 40, 50, 60], entraxe: ['4x108', '5x112', '5x120', '5x114.3'] },
    pair: { pouces: 'dim' },
    q: ['alloy wheels tires', 'car rims set'], photos: [2, 4],
  }),
  V('pieces-auto', 3, {
    title: 'Coffre de toit {marque} {litres} L',
    desc: 'Coffre de toit {marque} {litres} litres, ouverture double côté, fixation rapide sur barres. Servi deux étés, quelques micro-rayures. Barres de toit non incluses.',
    price: [150, 390], cond: BON,
    attrs: { type_piece: 'Autre', compatibilite: 'Barres de toit universelles' },
    opts: { marque: ['Thule', 'Norauto', 'Hapro', 'Menabo'], litres: [320, 400, 450, 500] },
    q: ['roof box car', 'car roof cargo box'], photos: [2, 3],
  }),
  V('pieces-auto', 3, {
    title: '{piece} {marque} {modele}, {etat}',
    desc: '{piece} pour {marque} {modele} {annees}, {etat}. Pièce d\'origine démontée d\'un véhicule accidenté à l\'arrière, référence visible sur la photo. Test possible avant enlèvement.',
    price: [45, 260], cond: ['bon_etat', 'etat_satisfaisant'],
    attrs: { type_piece: '{typePiece}', compatibilite: '{marque} {modele} {annees}' },
    opts: { piece: ['Phare avant droit', 'Rétroviseur gauche', 'Autoradio', 'Alternateur', 'Pare-chocs avant'], typePiece: ['Éclairage', 'Carrosserie', 'Électronique', 'Moteur', 'Carrosserie'], marque: ['Renault', 'Peugeot', 'Citroën', 'Volkswagen'], modele: ['Mégane', '308', 'C4', 'Polo'], annees: ['2012-2016', '2014-2019', '2016-2020', '2018-2022'], etat: ['fonctionnel', 'bon état', 'sans casse'] },
    pair: { piece: 'typePiece', marque: 'modele' },
    q: ['car headlight part', 'car side mirror', 'car radio dashboard', 'car alternator', 'car front bumper'], qByOpt: 'piece', qFallback: ['car spare parts'], photos: [2, 3],
  }),

  // ---------------------------------------------------------------- Immobilier (35)
  V('ventes-immobilieres', 4, {
    title: 'Appartement T{pieces} {surface} m² {quartier}, {ext}',
    desc: 'Appartement T{pieces} de {surface} m² au {etage}e étage {asc}, {ext}, cuisine {cuisine}, {chambres} chambre{s}. Copropriété bien tenue, charges {charges} €/mois, DPE {dpe}. Proche commerces, écoles et transports. Honoraires à la charge du vendeur.',
    price: [165000, 420000], noCondition: true, priceType: 'fixe',
    attrs: { type_bien: 'Appartement', surface: '{surface}', pieces: '{pieces}', chambres: '{chambres}', etage: '{etage}', ascenseur: '{ascBool}', exterieur: '{extAttr}', dpe: '{dpe}', ges: '{ges}', type_vente: 'Ancien', etat_bien: 'Bon état', exposition: '{expo}' },
    opts: { pieces: [2, 3, 4], surface: [46, 62, 78, 91], chambres: [1, 2, 3], s: ['', 's', 's'], quartier: ['proche centre', 'quartier calme', 'proche gare', 'vue dégagée'], ext: ['balcon exposé sud', 'terrasse de 12 m²', 'sans vis-à-vis', 'balcon filant'], extAttr: ['Balcon', 'Terrasse', 'Aucun', 'Balcon'], etage: [1, 2, 3, 4, 5], asc: ['avec ascenseur', 'sans ascenseur', 'avec ascenseur'], ascBool: [true, false, true], cuisine: ['équipée', 'ouverte équipée', 'aménagée'], charges: [110, 150, 190, 240], dpe: ['C', 'D', 'D', 'E'], ges: ['B', 'C', 'D', 'D'], expo: ['Sud', 'Sud-Ouest', 'Est', 'Ouest'] },
    pair: { pieces: 'chambres', chambres: 's', ext: 'extAttr', asc: 'ascBool' },
    q: ['apartment living room bright', 'modern apartment interior'], photos: [3, 5],
  }),
  V('ventes-immobilieres', 4, {
    title: 'Maison {pieces} pièces {surface} m² avec jardin, {commune}',
    desc: 'Maison familiale de {surface} m² sur un terrain de {terrain} m², {chambres} chambres, séjour lumineux, cuisine équipée, garage. Construite en {annee}, {etat}. Jardin clos arboré, quartier résidentiel calme. DPE {dpe}.',
    price: [235000, 520000], noCondition: true,
    attrs: { type_bien: 'Maison', surface: '{surface}', pieces: '{pieces}', chambres: '{chambres}', salles_eau: 2, exterieur: 'Jardin', dpe: '{dpe}', ges: '{ges}', surface_terrain: '{terrain}', annee_construction: '{annee}', type_vente: 'Ancien', etat_bien: '{etatAttr}' },
    opts: { pieces: [4, 5, 6], surface: [95, 110, 128, 145], chambres: [3, 4, 4], terrain: [380, 520, 700, 950], annee: [1978, 1995, 2006, 2015], etat: ['toiture et chaudière récentes', 'entièrement rénovée en 2021', 'quelques rafraîchissements à prévoir'], etatAttr: ['Bon état', 'Neuf / rénové', 'À rénover'], commune: ['périphérie', 'village à 15 min', 'proche écoles'], dpe: ['C', 'D', 'E'], ges: ['B', 'C', 'D'] },
    pair: { pieces: 'chambres', etat: 'etatAttr' },
    q: ['french house garden', 'family house exterior'], photos: [3, 5],
  }),
  V('locations', 6, {
    title: 'T{pieces} {surface} m² {meuble}, {quartier}',
    desc: 'Appartement T{pieces} de {surface} m² {meuble}, {etage}e étage, {chauffage}, cuisine équipée, {ext}. Loyer {loyerTxt} € charges comprises ({charges} € de charges), dépôt de garantie un mois. Disponible le {dispo}. Dossier complet demandé (justificatifs de revenus, garant).',
    price: [520, 1250], noCondition: true,
    attrs: { type_bien: 'Appartement', surface: '{surface}', pieces: '{pieces}', chambres: '{chambres}', etage: '{etage}', ascenseur: '{asc}', exterieur: '{extAttr}', dpe: '{dpe}', ges: '{ges}', meuble: '{meubleBool}', charges: '{charges}', depot_garantie: '{depot}', disponible_le: '{dispo}' },
    opts: { pieces: [1, 2, 3], surface: [24, 42, 64], chambres: [0, 1, 2], meuble: ['meublé', 'non meublé', 'meublé'], meubleBool: [true, false, true], quartier: ['proche métro', 'centre-ville', 'quartier étudiant', 'proche tramway'], etage: [1, 2, 3, 4], asc: [true, false, true, true], chauffage: ['chauffage individuel gaz', 'chauffage collectif', 'chauffage électrique'], ext: ['balcon', 'sans extérieur', 'petite terrasse'], extAttr: ['Balcon', 'Aucun', 'Terrasse'], charges: [45, 70, 95, 120], depot: [520, 780, 1100], dispo: ['1er novembre 2026', '15 octobre 2026', '1er décembre 2026', 'immédiatement'], dpe: ['C', 'D', 'E'], ges: ['B', 'C', 'C'], loyerTxt: ['voir prix', 'indiqué', 'indiqué'] },
    pair: { pieces: 'surface', surface: 'chambres', meuble: 'meubleBool', ext: 'extAttr' },
    q: ['apartment for rent interior', 'studio apartment bright'], photos: [3, 5],
  }),
  V('locations', 5, {
    title: 'Studio {surface} m² meublé, {quartier}',
    desc: 'Studio meublé de {surface} m² au {etage}e étage, kitchenette équipée, salle d\'eau avec douche, lit {lit}, bureau, placard. {internet}. Loyer charges comprises (eau, chauffage, entretien des parties communes). Idéal étudiant ou jeune actif. Disponible le {dispo}.',
    price: [420, 720], noCondition: true,
    attrs: { type_bien: 'Appartement', surface: '{surface}', pieces: 1, chambres: 0, etage: '{etage}', ascenseur: false, exterieur: 'Aucun', dpe: '{dpe}', ges: '{ges}', meuble: true, charges: '{charges}', depot_garantie: '{depot}', disponible_le: '{dispo}' },
    opts: { surface: [18, 21, 24, 27], quartier: ['proche fac', 'centre', 'proche gare', 'quartier calme'], etage: [1, 2, 3], lit: ['140', '160', '120'], internet: ['Fibre incluse', 'Connexion fibre à la charge du locataire', 'Wifi inclus'], dispo: ['1er octobre 2026', '15 octobre 2026', '1er novembre 2026'], dpe: ['D', 'E', 'C'], ges: ['B', 'C', 'B'], charges: [40, 55, 70], depot: [420, 500, 600] },
    q: ['small studio apartment', 'studio flat bed desk'], photos: [2, 4],
  }),
  V('locations', 4, {
    title: 'Maison {pieces} pièces avec jardin à louer, {commune}',
    desc: 'Maison de {surface} m² avec jardin de {terrain} m², {chambres} chambres, garage, cuisine équipée, {chauffage}. Location non meublée, bail 3 ans. Loyer hors charges, taxe d\'ordures ménagères refacturée. Visites à partir du {dispo}.',
    price: [890, 1650], noCondition: true,
    attrs: { type_bien: 'Maison', surface: '{surface}', pieces: '{pieces}', chambres: '{chambres}', etage: 0, ascenseur: false, exterieur: 'Jardin', dpe: '{dpe}', ges: '{ges}', meuble: false, charges: '{charges}', depot_garantie: '{depot}', disponible_le: '{dispo}' },
    opts: { pieces: [4, 5], surface: [88, 105, 120], terrain: [300, 450, 600], chambres: [3, 4], commune: ['proche commodités', 'village calme', 'entrée de ville'], chauffage: ['pompe à chaleur', 'chaudière gaz récente', 'poêle à granulés + électrique'], dispo: ['1er novembre 2026', '15 novembre 2026', '1er décembre 2026'], dpe: ['C', 'D'], ges: ['B', 'C'], charges: [30, 45], depot: [890, 1200, 1500] },
    pair: { pieces: 'chambres' },
    q: ['house with garden', 'suburban house exterior'], photos: [3, 4],
  }),
  V('colocations', 6, {
    title: 'Chambre {surface} m² en colocation, {quartier}',
    desc: 'Chambre meublée de {surface} m² dans un {logement} partagé avec {coloc} colocataire{s} ({profil}). Cuisine équipée, salle de bain commune, machine à laver, fibre. Loyer charges et internet compris. Ambiance respectueuse, non fumeur. Disponible le {dispo}.',
    price: [380, 620], noCondition: true,
    attrs: { surface: '{surface}', colocataires: '{coloc}', meuble: true, charges: '{charges}', dpe: '{dpe}' },
    opts: { surface: [10, 12, 14, 16], logement: ['T4', 'T5', 'grande maison'], coloc: [2, 3, 4], s: ['s', 's', 's'], profil: ['étudiants', 'jeunes actifs', 'étudiants et un jeune actif'], quartier: ['proche campus', 'centre', 'proche tram', 'quartier animé'], dispo: ['1er octobre 2026', '15 octobre 2026', '1er novembre 2026'], charges: [50, 60, 75], dpe: ['C', 'D'] },
    pair: { coloc: 's' },
    q: ['bedroom shared apartment', 'cozy bedroom desk'], photos: [2, 4],
  }),
  V('bureaux-commerces', 3, {
    title: '{type} {surface} m² {transaction}, {quartier}',
    desc: '{type} de {surface} m² {transaction}, {etat}. {detail} Stationnement à proximité, accès PMR. Bail commercial 3-6-9 ou cession, selon le projet. Visite sur rendez-vous.',
    price: [950, 185000], noCondition: true,
    attrs: { type_local: '{typeAttr}', surface: '{surface}', transaction: '{transAttr}' },
    opts: { type: ['Local commercial', 'Bureaux', 'Entrepôt'], typeAttr: ['Local commercial', 'Bureau', 'Entrepôt'], surface: [45, 80, 220], transaction: ['à louer', 'à vendre', 'à louer'], transAttr: ['Location', 'Vente', 'Location'], quartier: ['rue passante', 'zone d\'activité', 'centre-ville'], etat: ['rénové en 2023', 'bon état général', 'à aménager'], detail: ['Vitrine de 6 m, réserve et sanitaires.', 'Open space, deux bureaux fermés, salle de réunion.', 'Porte sectionnelle, hauteur 6 m, bureau attenant.'] },
    pair: { type: 'typeAttr', transaction: 'transAttr', type2: 'detail' },
    q: ['empty shop retail space', 'office space empty', 'warehouse interior'], qByOpt: 'type', photos: [2, 4],
  }),
  V('terrains', 3, {
    title: 'Terrain {constructible} de {surface} m², {commune}',
    desc: 'Terrain {constructible} de {surface} m², {viab}, {forme}. Certificat d\'urbanisme disponible, accès direct par la route communale. Environnement calme, écoles et commerces à quelques minutes.',
    price: [39000, 145000], noCondition: true,
    attrs: { surface_terrain: '{surface}', constructible: '{constBool}', viabilise: '{viabBool}' },
    opts: { constructible: ['constructible', 'constructible', 'de loisirs non constructible'], constBool: [true, true, false], surface: [520, 780, 1100, 2400], viab: ['viabilisé (eau, électricité, tout-à-l\'égout en limite)', 'à viabiliser', 'viabilisé'], viabBool: [true, false, true], forme: ['plat et rectangulaire', 'en légère pente exposée sud', 'bordé de haies'], commune: ['village à 20 min de la ville', 'hameau calme', 'lotissement récent'] },
    pair: { constructible: 'constBool', viab: 'viabBool' },
    q: ['building plot land for sale', 'green field meadow'], photos: [2, 3],
  }),

  // ---------------------------------------------------------------- Emploi (15)
  V('offres-emploi', 12, {
    title: '{poste} — {contrat}{temps}',
    desc: '{structure} recrute un(e) {poste} en {contrat}{temps}. {missions} Profil : {profil}. Rémunération {remu}, {avantages}. Poste à pourvoir {dispo}. Candidature (CV et quelques lignes de motivation) par la messagerie.',
    priceType: 'sur_demande', noCondition: true,
    attrs: { contrat: '{contrat}', temps: '{tempsAttr}', secteur: '{secteur}', experience: '{exp}', fonction: '{poste}', niveau_etudes: '{niveau}', teletravail: '{tele}' },
    opts: { poste: ['Vendeur(se) en boulangerie', 'Serveur(se)', 'Développeur(se) web', 'Aide à domicile', 'Cariste', 'Assistant(e) administratif(ve)', 'Mécanicien(ne) auto', 'Auxiliaire de crèche', 'Commercial(e) terrain', 'Cuisinier(ère)', 'Chauffeur-livreur', 'Comptable'], secteur: ['Commerce', 'Restauration', 'Informatique', 'Services à la personne', 'Logistique', 'Administratif', 'Automobile', 'Petite enfance', 'Commerce', 'Restauration', 'Transport', 'Comptabilité'], structure: ['Boulangerie artisanale', 'Brasserie de centre-ville', 'Agence web de 12 personnes', 'Association d\'aide à domicile', 'Plateforme logistique', 'Cabinet d\'expertise', 'Garage indépendant', 'Micro-crèche', 'PME de menuiserie', 'Restaurant traditionnel', 'Société de livraison', 'Cabinet comptable'], missions: ['Accueil, vente, mise en rayon et tenue de la boutique.', 'Service en salle et en terrasse, prise de commandes, encaissement.', 'Développement d\'applications web (TypeScript, React, Node), revues de code, déploiements.', 'Aide aux gestes du quotidien, courses, entretien du logement, accompagnement.', 'Chargement, déchargement, préparation de commandes, conduite de chariot (CACES 1-3).', 'Gestion du courrier, facturation, suivi des dossiers, accueil téléphonique.', 'Diagnostic, entretien courant, freinage, distribution, préparation au contrôle technique.', 'Accueil des enfants et des familles, activités d\'éveil, hygiène et repas.', 'Prospection, rendez-vous clients, devis, suivi du portefeuille.', 'Préparation des plats, mise en place, respect des normes HACCP.', 'Tournées de livraison en ville, manutention, relation client.', 'Saisie, rapprochements bancaires, déclarations de TVA, préparation des bilans.'], contrat: ['CDI', 'CDD', 'CDI', 'Intérim', 'CDI', 'Alternance', 'CDI', 'CDD', 'CDI', 'Saisonnier', 'CDI', 'CDI'], temps: ['', ' temps partiel (28 h)', '', '', '', '', '', ' temps partiel', '', '', '', ''], tempsAttr: ['Temps plein', 'Temps partiel', 'Temps plein', 'Temps plein', 'Temps plein', 'Temps plein', 'Temps plein', 'Temps partiel', 'Temps plein', 'Temps plein', 'Temps plein', 'Temps plein'], exp: ['Débutant accepté', 'Débutant accepté', '1 à 3 ans', 'Débutant accepté', '1 à 3 ans', '1 à 3 ans', '3 à 5 ans', '1 à 3 ans', '1 à 3 ans', '3 à 5 ans', 'Débutant accepté', '3 à 5 ans'], profil: ['souriant(e), ponctuel(le), sens du service', 'dynamique, à l\'aise avec le rythme du service', 'autonome, curieux(se), 2 ans d\'expérience minimum', 'bienveillant(e), permis B apprécié', 'CACES à jour, rigueur', 'organisé(e), bonne orthographe, maîtrise des outils bureautiques', 'CAP/Bac pro maintenance, autonome', 'CAP AEPE exigé', 'permis B, goût du contact', 'expérience en cuisine traditionnelle', 'permis B depuis plus de 3 ans', 'BTS comptabilité ou DCG'], niveau: ['CAP / BEP', 'Sans diplôme', 'Bac +3', 'Sans diplôme', 'CAP / BEP', 'Bac +2', 'CAP / BEP', 'CAP / BEP', 'Bac +2', 'CAP / BEP', 'Sans diplôme', 'Bac +2'], remu: ['SMIC + primes', 'selon expérience', '38 à 46 k€ selon profil', 'SMIC + indemnités kilométriques', '12,20 €/h + paniers', '1 900 à 2 200 € brut', '2 100 à 2 600 € brut', 'convention collective', 'fixe + variable', '2 000 à 2 300 € brut', 'SMIC + primes', '2 300 à 2 800 € brut'], avantages: ['mutuelle et pain offert', 'pourboires, deux jours de repos consécutifs', 'télétravail 3 jours par semaine', 'véhicule de service', 'tickets restaurant', 'mutuelle, 13e mois', 'formation continue', 'horaires réguliers', 'véhicule de fonction', 'repas sur place', 'véhicule fourni', 'télétravail partiel'], tele: [false, false, true, false, false, false, false, false, false, false, false, true], dispo: ['immédiatement', 'dès que possible', 'au 1er novembre', 'en janvier'] },
    pair: { poste: 'secteur', poste2: 'structure', poste3: 'missions', poste4: 'contrat', poste5: 'temps', poste6: 'tempsAttr', poste7: 'exp', poste8: 'profil', poste9: 'niveau', poste10: 'remu', poste11: 'avantages', poste12: 'tele' },
    q: ['bakery shop counter', 'restaurant waiter service', 'developer laptop office', 'home care elderly help', 'warehouse forklift', 'office desk administrative', 'car mechanic garage', 'nursery children playing', 'sales meeting handshake', 'chef kitchen cooking', 'delivery van driver', 'accountant office documents'], qByOpt: 'poste', photos: [2, 3],
  }),
  V('formations', 3, {
    title: 'Formation {theme} — {duree}',
    desc: 'Formation {type} en {theme}, {duree}, en petit groupe ({places} places). {contenu} Éligible au CPF, attestation en fin de parcours. Sessions à partir de {mois}. Programme détaillé sur demande.',
    price: [390, 1490], noCondition: true,
    attrs: { type_formation: '{typeAttr}', duree: '{duree}' },
    opts: { theme: ['création de site web', 'anglais professionnel', 'gestes de premiers secours (PSC1)'], type: ['certifiante', 'certifiante', 'courte'], typeAttr: ['Certifiante', 'Certifiante', 'Courte'], duree: ['5 jours', '30 heures', '1 journée'], places: [8, 10, 12], contenu: ['HTML, CSS, bases de JavaScript, mise en ligne.', 'Conversation, e-mails, réunions, préparation au TOEIC.', 'Alerte, protection, gestes qui sauvent, mises en situation.'], mois: ['octobre', 'novembre', 'janvier'] },
    pair: { theme: 'type', theme2: 'typeAttr', theme3: 'duree', theme4: 'contenu' },
    q: ['training classroom adults', 'workshop learning group'], photos: [2, 3],
  }),

  // ---------------------------------------------------------------- Matériel professionnel (20)
  V('btp', 6, {
    title: '{materiel} {marque}, {annee}',
    desc: '{materiel} {marque} de {annee}, {heures} heures, {etat}. Révision récente, {detail}. Vendu pour cessation partielle d\'activité, facture fournie. Chargement possible sur place.',
    price: [1900, 24900], cond: BON,
    attrs: { type_materiel: '{typeAttr}', marque: '{marque}', annee: '{annee}', heures: '{heures}' },
    opts: { materiel: ['Mini-pelle 1,5 t', 'Compresseur de chantier', 'Échafaudage roulant 8 m', 'Plaque vibrante 150 kg', 'Groupe électrogène 6 kVA', 'Bétonnière 350 L'], typeAttr: ['Engin de chantier', 'Outillage', 'Échafaudage', 'Outillage', 'Outillage', 'Outillage'], marque: ['Kubota', 'Atlas Copco', 'Layher', 'Wacker Neuson', 'SDMO', 'Imer'], annee: [2016, 2018, 2019, 2020, 2021], heures: [1800, 950, 0, 420, 610, 0], etat: ['très bon état général', 'bon état, traces d\'usage normales', 'complet avec plateaux et garde-corps'], detail: ['godets de 30 et 60 cm inclus', 'flexibles neufs', 'notice et certificat de conformité fournis'] },
    pair: { materiel: 'typeAttr', materiel2: 'marque', materiel3: 'heures' },
    q: ['mini excavator construction', 'air compressor construction site', 'mobile scaffolding', 'plate compactor', 'generator construction', 'concrete mixer'], qByOpt: 'materiel', photos: [2, 4],
  }),
  V('agricole', 4, {
    title: '{materiel} {marque} {annee}',
    desc: '{materiel} {marque} de {annee}, {heures}, {detail}. Matériel entretenu, remisé sous hangar, prêt à travailler. Visible et essayable sur l\'exploitation.',
    price: [2400, 38000], cond: BON,
    attrs: { type_materiel: '{typeAttr}', marque: '{marque}', annee: '{annee}', heures: '{heuresAttr}', puissance: '{puissance}' },
    opts: { materiel: ['Tracteur', 'Remorque benne 8 t', 'Girobroyeur 1,80 m', 'Semoir à céréales 3 m'], typeAttr: ['Tracteur', 'Remorque', 'Outil de travail du sol', 'Semis / Récolte'], marque: ['Massey Ferguson', 'Rolland', 'Desvoys', 'Kuhn'], annee: [2004, 2012, 2016, 2019], heures: ['6 800 heures', 'pneus récents', 'lames neuves', 'compteur d\'hectares'], heuresAttr: [6800, 0, 0, 0], detail: ['4 roues motrices, chargeur frontal', 'freinage hydraulique, bâche', 'boîtier neuf', 'traceurs hydrauliques'], puissance: [95, 1, 1, 1] },
    pair: { materiel: 'typeAttr', materiel2: 'marque', materiel3: 'heures', materiel4: 'heuresAttr', materiel5: 'detail', materiel6: 'puissance' },
    q: ['farm tractor field', 'farm trailer', 'rotary mower agriculture', 'seed drill agriculture'], qByOpt: 'materiel', photos: [2, 4],
  }),
  V('restauration-hotellerie', 5, {
    title: '{materiel} professionnel {marque}',
    desc: '{materiel} professionnel {marque}, {age}, {etat}. Utilisé dans notre {lieu} jusqu\'à sa fermeture. Fonctionnement vérifié, {detail}. Enlèvement par vos soins.',
    price: [350, 4900], cond: BON,
    attrs: { type_materiel: '{typeAttr}', marque: '{marque}' },
    opts: { materiel: ['Four mixte 6 niveaux', 'Armoire réfrigérée 700 L', 'Lave-vaisselle à capot', 'Machine à café 2 groupes', 'Lot de 20 chaises et 6 tables'], typeAttr: ['Cuisson', 'Froid', 'Lavage', 'Bar / Café', 'Mobilier'], marque: ['Rational', 'Liebherr', 'Hobart', 'La Marzocco', 'Bolero'], age: ['de 2019', 'de 2020', 'de 2018', 'de 2021', 'récent'], etat: ['très bon état', 'bon état', 'état impeccable'], lieu: ['restaurant', 'brasserie', 'café', 'traiteur'], detail: ['dernier contrôle en juin', 'joints et thermostat neufs', 'notice fournie'] },
    pair: { materiel: 'typeAttr', materiel2: 'marque' },
    q: ['commercial kitchen oven', 'commercial refrigerator stainless', 'commercial dishwasher', 'espresso machine cafe', 'restaurant chairs tables'], qByOpt: 'materiel', photos: [2, 4],
  }),
  V('fournitures-bureau', 5, {
    title: '{lot}, {etat}',
    desc: '{lot} — {detail}. Provenance : déménagement de nos bureaux. Enlèvement à prévoir sur place, possibilité de charger sur palette. Facture disponible.',
    price: [120, 1500], cond: BON,
    attrs: { type_fourniture: '{typeAttr}', marque: '{marque}', quantite: '{qte}' },
    opts: { lot: ['Lot de 10 fauteuils de bureau', 'Photocopieur multifonction A3', '6 bureaux réglables en hauteur', 'Lot de 4 armoires métalliques', 'Écrans 24" (lot de 8)'], typeAttr: ['Mobilier de bureau', 'Machines (photocopieur, plastifieuse…)', 'Mobilier de bureau', 'Mobilier de bureau', 'Informatique / Bureautique'], marque: ['Steelcase', 'Canon', 'Ikea', 'Bisley', 'Dell'], qte: [10, 1, 6, 4, 8], etat: ['bon état', 'très bon état', 'état correct'], detail: ['dossier réglable, accoudoirs, roulettes silencieuses', '35 pages/minute, recto-verso, réseau, compteur 140 000 pages', 'plateau 160 × 80, moteur électrique, mémoire de positions', 'portes à rideau, clés fournies', 'Full HD, dalle IPS, pieds réglables'] },
    pair: { lot: 'typeAttr', lot2: 'marque', lot3: 'qte', lot4: 'detail' },
    q: ['office chairs', 'office photocopier', 'standing desk office', 'metal filing cabinet', 'computer monitors office'], qByOpt: 'lot', photos: [2, 4],
  }),

  // ---------------------------------------------------------------- Locations de vacances (10)
  V('vacances', 10, {
    title: '{hebergement} {lieu}, {capacite}',
    desc: '{hebergement} pour {capacite} {lieu} : {detail}. {equip} Draps et serviettes fournis, arrivée à partir de 16 h. Prix indiqué par semaine, {saison}. Taxe de séjour en sus.',
    price: [450, 2200], noCondition: true,
    attrs: { type_hebergement: '{typeAttr}', environnement: '{env}', voyageurs: '{voyageurs}', piscine: '{piscine}', jardin: '{jardin}', wifi: true, parking: true, animaux_acceptes: '{animaux}', chambres: '{chambres}' },
    opts: { hebergement: ['Appartement', 'Maison', 'Chalet', 'Mobil-home', 'Gîte', 'Villa', 'Studio', 'Chambre d\'hôtes', 'Roulotte', 'Appartement'], typeAttr: ['Appartements', 'Maisons et villas', 'Chalets', 'Mobil-homes', 'Maisons et villas', 'Maisons et villas', 'Appartements', 'Chambres d\'hôtes', 'Hébergements insolites', 'Appartements'], lieu: ['à 300 m de la plage (Vendée)', 'en Dordogne', 'aux Deux Alpes', 'dans un camping 4 étoiles (Landes)', 'en Bretagne sud', 'avec piscine près d\'Uzès', 'au cœur d\'Annecy', 'en Alsace', 'dans le Luberon', 'à Biarritz'], env: ['Mer', 'Campagne', 'Montagne', 'Mer', 'Mer', 'Campagne', 'Lac / Rivière', 'Campagne', 'Campagne', 'Mer'], capacite: ['4 personnes', '6 personnes', '8 personnes', '6 personnes', '5 personnes', '8 personnes', '2 personnes', '2 personnes', '4 personnes', '4 personnes'], voyageurs: ['À quatre', 'À six', 'Plus de six', 'À six', 'À six', 'Plus de six', 'À deux', 'À deux', 'À quatre', 'À quatre'], detail: ['deux chambres, balcon vue mer, parking privé', 'maison en pierre, grand jardin, barbecue', 'chalet skis aux pieds, sauna, garage', 'terrasse couverte, plancha, accès piscine du camping', 'longère rénovée à 10 min des plages', 'villa de plain-pied, piscine chauffée, cuisine d\'été', 'studio rénové à 5 min du lac, vélos à disposition', 'chambre avec petit-déjeuner maison, jardin', 'roulotte tout confort au bord de la rivière', 'appartement lumineux à 10 min à pied de la Grande Plage'], equip: ['Lave-linge, lave-vaisselle, TV.', 'Wifi, lave-vaisselle, lits faits à l\'arrivée.', 'Local à skis, wifi, TV.', 'Climatisation, TV, wifi.', 'Poêle à bois, wifi, jeux de société.', 'Climatisation, wifi, barbecue.', 'Wifi, TV, cuisine équipée.', 'Wifi, parking, petit-déjeuner inclus.', 'Kitchenette, sanitaires privés.', 'Ascenseur, wifi, TV.'], piscine: [false, false, false, true, false, true, false, false, false, false], jardin: [false, true, false, false, true, true, false, true, true, false], animaux: [false, true, false, false, true, false, false, false, true, false], chambres: [2, 3, 3, 2, 3, 4, 0, 1, 1, 2], saison: ['hors juillet-août', 'en haute saison', 'en saison', 'hors vacances scolaires'] },
    pair: { hebergement: 'typeAttr', hebergement2: 'lieu', hebergement3: 'env', hebergement4: 'capacite', hebergement5: 'voyageurs', hebergement6: 'detail', hebergement7: 'equip', hebergement8: 'piscine', hebergement9: 'jardin', hebergement10: 'animaux', hebergement11: 'chambres' },
    q: ['beach apartment balcony sea', 'stone house countryside france', 'alpine chalet snow', 'mobile home campsite', 'brittany cottage', 'villa with pool provence', 'lake annecy apartment', 'bed and breakfast room', 'gypsy caravan glamping', 'biarritz apartment'], qByOpt: 'hebergement', photos: [3, 5],
    city: ['sables', 'sarlat', 'deuxalpes', 'mimizan', 'vannes', 'uzes', 'annecy', 'colmar', 'gordes', 'biarritz'], cityByOpt: 'hebergement',
  }),

  // ---------------------------------------------------------------- Services (30)
  V('cours-particuliers', 6, {
    title: 'Cours particuliers de {matiere} — {niveau}',
    desc: '{qui}, je propose des cours de {matiere} pour {niveauTxt}. {methode} Tarif {tarif} € de l\'heure, première séance de découverte à moitié prix. {lieu}',
    price: [18, 35], noCondition: true, priceType: 'fixe',
    attrs: { matiere: '{matiere}', niveau: '{niveau}', a_distance: '{distance}', tarif_type: 'Horaire' },
    opts: { matiere: ['Mathématiques', 'Anglais', 'Français', 'Physique-chimie', 'Espagnol', 'Informatique / Programmation'], niveau: ['Lycée', 'Collège', 'Primaire', 'Lycée', 'Adulte', 'Supérieur'], niveauTxt: ['lycéens (seconde à terminale, préparation au bac)', 'collégiens (remise à niveau, brevet)', 'enfants du primaire (lecture, écriture)', 'lycéens et prépas', 'adultes (conversation, voyages, travail)', 'étudiants et reconversions'], qui: ['Étudiant en master', 'Professeure certifiée', 'Enseignante retraitée', 'Ingénieur', 'Locutrice native', 'Développeur professionnel'], methode: ['Méthode adaptée au rythme de chacun, exercices corrigés entre les séances.', 'Suivi régulier et bilan aux parents chaque mois.', 'Approche ludique et progressive.', 'Préparation aux contrôles et aux examens.', 'Conversation à 80 % de la séance.', 'Projets concrets dès le premier cours.'], tarif: [22, 25, 20, 28, 24, 30], distance: [true, false, false, true, true, true], lieu: ['À domicile ou en visio.', 'À domicile dans un rayon de 10 km.', 'À mon domicile, quartier calme.', 'En visio ou à domicile.', 'En visio uniquement.', 'En visio ou dans un café.'] },
    pair: { matiere: 'niveau', matiere2: 'niveauTxt', matiere3: 'qui', matiere4: 'methode', matiere5: 'tarif', matiere6: 'distance', matiere7: 'lieu' },
    q: ['tutoring student desk', 'teacher explaining notebook'], photos: [2, 3],
  }),
  V('demenagement', 3, {
    title: 'Déménagement avec {vehicule} et {bras} bras',
    desc: 'Je propose mes services pour vos déménagements avec {vehicule} et {bras} personnes, {zone}. Chargement, transport, déchargement, démontage simple. Matériel fourni (diable, sangles, couvertures). Tarif {tarif}, devis gratuit par messagerie.',
    price: [45, 90], noCondition: true,
    attrs: { vehicule: '{vehAttr}', zone: '{zoneAttr}', tarif_type: 'Horaire' },
    opts: { vehicule: ['utilitaire 12 m³', 'camion 20 m³ avec hayon', 'utilitaire 12 m³'], vehAttr: ['Utilitaire 12 m³', 'Camion 20 m³', 'Utilitaire 12 m³'], bras: [2, 3, 2], zone: ['dans toute l\'agglomération et jusqu\'à 100 km', 'en région et longue distance sur devis', 'dans un rayon de 50 km'], zoneAttr: ['Agglomération + 100 km', 'Région et longue distance', 'Rayon de 50 km'], tarif: ['horaire (2 h minimum)', 'horaire, forfait possible', 'horaire'] },
    pair: { vehicule: 'vehAttr', vehicule2: 'bras', zone: 'zoneAttr' },
    q: ['moving boxes van', 'movers carrying furniture'], photos: [2, 3],
  }),
  V('jardinerie-bricolage', 4, {
    title: '{metier} — {prestation}',
    desc: '{metier} {statut}, je propose : {prestation}. {detail} Intervention rapide, travail soigné, devis gratuit. Facture et garantie décennale pour les travaux concernés.',
    price: [25, 45], noCondition: true,
    attrs: { metier: '{metierAttr}', tarif_type: '{tarifType}', zone: '{zone}' },
    opts: { metier: ['Jardinier', 'Peintre', 'Plombier', 'Bricoleur'], metierAttr: ['Jardinier', 'Peintre', 'Plombier', 'Bricoleur'], statut: ['auto-entrepreneur', 'à mon compte depuis 8 ans', 'artisan', 'multiservices'], prestation: ['tonte, taille de haies, débroussaillage, évacuation des déchets verts', 'peinture intérieure, enduits, pose de papier peint', 'dépannage fuites, remplacement de robinetterie, chauffe-eau', 'montage de meubles, fixations, petites réparations'], detail: ['Matériel professionnel, possibilité de contrat d\'entretien à l\'année.', 'Protection des sols et des meubles, chantier propre.', 'Déplacement dans l\'heure pour les urgences.', 'Pas de minimum, j\'aime les petits travaux que personne ne veut faire.'], tarifType: ['Horaire', 'Sur devis', 'Sur devis', 'Horaire'], zone: ['30 km autour de la ville', 'Agglomération', 'Ville et proche banlieue', '20 km'] },
    pair: { metier: 'metierAttr', metier2: 'statut', metier3: 'prestation', metier4: 'detail', metier5: 'tarifType', metier6: 'zone' },
    q: ['gardener hedge trimming', 'painter painting wall', 'plumber fixing sink', 'handyman assembling furniture'], qByOpt: 'metier', photos: [2, 3],
  }),
  V('services-a-la-personne', 4, {
    title: '{service} — {dispo}',
    desc: '{qui}, je propose {serviceTxt}. {detail} Sérieux, ponctualité et discrétion. Paiement CESU accepté. Références disponibles sur demande.',
    price: [13, 22], noCondition: true,
    attrs: { type_service: '{typeAttr}', tarif_type: 'Horaire', zone: '{zone}' },
    opts: { service: ['Ménage et repassage', 'Aide à domicile pour personnes âgées', 'Garde d\'animaux', 'Aide aux courses et accompagnement'], serviceTxt: ['des prestations de ménage et de repassage à domicile', 'une aide à domicile pour personnes âgées ou en convalescence', 'la garde de vos animaux à votre domicile ou chez moi', 'de l\'aide aux courses, aux démarches et de l\'accompagnement aux rendez-vous'], typeAttr: ['Ménage', 'Aide à domicile', 'Garde d\'animaux', 'Aide à domicile'], qui: ['Employée de maison expérimentée', 'Auxiliaire de vie diplômée', 'Amoureuse des animaux', 'Retraitée dynamique'], detail: ['Produits fournis ou les vôtres, selon préférence.', 'Aide à la toilette, aux repas, à la mobilité.', 'Promenades, soins, nuits possibles.', 'Véhiculée, disponible en semaine.'], dispo: ['semaine et samedi matin', 'du lundi au vendredi', 'week-ends et vacances', 'matinées en semaine'], zone: ['Ville et alentours', '15 km', 'Quartier et communes limitrophes', 'Agglomération'] },
    pair: { service: 'serviceTxt', service2: 'typeAttr', service3: 'qui', service4: 'detail', service5: 'dispo', service6: 'zone' },
    q: ['house cleaning service', 'elderly care companion', 'dog walker', 'grocery shopping help'], qByOpt: 'service', photos: [2, 3],
  }),
  V('baby-sitting', 3, {
    title: 'Baby-sitting {dispo}, {exp}',
    desc: '{qui}, je garde vos enfants {dispo} : sorties d\'école, soirées, mercredis. {detail} Non fumeuse, {vehicule}, références vérifiables. Tarif horaire, majoré après 22 h.',
    price: [11, 15], noCondition: true,
    attrs: { experience: '{expAttr}', vehicule: '{vehBool}', tarif_type: 'Horaire' },
    opts: { dispo: ['en soirée et le week-end', 'après l\'école et le mercredi', 'pendant les vacances'], exp: ['3 ans d\'expérience', 'diplômée petite enfance', 'étudiante sérieuse'], expAttr: ['1 à 3 ans', 'Diplômé petite enfance', 'Débutant'], qui: ['Étudiante en psychologie', 'Assistante maternelle agréée', 'Étudiante infirmière'], detail: ['Aide aux devoirs et jeux calmes avant le coucher.', 'Activités manuelles, sorties au parc, respect des rythmes.', 'Formée aux gestes de premiers secours.'], vehicule: ['véhiculée', 'non véhiculée (transports en commun)', 'véhiculée'], vehBool: [true, false, true] },
    pair: { dispo: 'exp', dispo2: 'expAttr', dispo3: 'qui', dispo4: 'detail', vehicule: 'vehBool' },
    q: ['babysitter playing with child', 'child drawing table'], photos: [2, 3],
  }),
  V('reparations-electroniques', 2, {
    title: 'Réparation {appareil} — {detail}',
    desc: 'Réparateur indépendant : {prestations}. Diagnostic gratuit, devis avant intervention, pièces de qualité garanties {garantie}. Atelier en centre-ville, dépôt et récupération sur rendez-vous.',
    priceType: 'sur_demande', noCondition: true,
    attrs: { appareils: '{appAttr}', tarif_type: 'Sur devis' },
    opts: { appareil: ['smartphones et tablettes', 'ordinateurs'], appAttr: ['Smartphone', 'Ordinateur'], detail: ['écran, batterie, connecteur', 'nettoyage, SSD, récupération de données'], prestations: ['remplacement d\'écran et de batterie en une heure, connecteur de charge, désoxydation', 'dépannage Windows et Mac, remplacement de disque par SSD, récupération de données, nettoyage de virus'], garantie: ['6 mois', '3 mois'] },
    pair: { appareil: 'appAttr', appareil2: 'detail', appareil3: 'prestations', appareil4: 'garantie' },
    q: ['smartphone repair technician', 'laptop repair workshop'], qByOpt: 'appareil', photos: [2, 3],
  }),
  V('covoiturage', 2, {
    title: 'Covoiturage {depart} → {arrivee} {jour}',
    desc: 'Trajet régulier {depart} → {arrivee}, départ {heure}, retour le {retour}. {places} places dans une voiture récente, non fumeur, bagage cabine accepté. Participation aux frais partagée, rendez-vous à la gare.',
    price: [12, 28], noCondition: true,
    attrs: { depart: '{depart}', arrivee: '{arrivee}', places: '{places}' },
    opts: { depart: ['Lyon', 'Nantes'], arrivee: ['Grenoble', 'Rennes'], jour: ['chaque vendredi', 'tous les dimanches soir'], heure: ['18 h 30', '19 h'], retour: ['dimanche soir', 'vendredi soir'], places: [3, 2] },
    pair: { depart: 'arrivee', depart2: 'jour', depart3: 'heure', depart4: 'retour', depart5: 'places' },
    city: ['lyon3', 'nantes'], cityByOpt: 'depart',
    q: ['carpooling highway car', 'car dashboard road trip'], photos: [2, 2],
  }),
  V('evenementiel', 2, {
    title: '{prestation} pour vos évènements',
    desc: '{prestation} pour mariages, anniversaires et soirées d\'entreprise : {detail}. Matériel professionnel, {garantie}. Devis personnalisé sous 48 h, disponibilités {dispo}.',
    priceType: 'sur_demande', noCondition: true,
    attrs: { type_prestation: '{typeAttr}', tarif_type: 'Sur devis' },
    opts: { prestation: ['DJ et sonorisation', 'Photographe'], typeAttr: ['DJ / Musicien', 'Photographe'], detail: ['playlist sur mesure, jeux de lumière, micro pour les discours', 'reportage complet, galerie en ligne, tirages possibles'], garantie: ['contrat et assurance', 'remise des photos sous 3 semaines'], dispo: ['2026 et 2027', 'sur toute la région'] },
    pair: { prestation: 'typeAttr', prestation2: 'detail', prestation3: 'garantie' },
    q: ['dj party lights', 'wedding photographer camera'], qByOpt: 'prestation', photos: [2, 3],
  }),
  V('entraide-voisins', 2, {
    title: '{aide} — entraide entre voisins',
    desc: '{texte} Gratuit ou en échange d\'un service, selon ce qui vous arrange. Je suis disponible {dispo}.',
    priceType: 'gratuit', noCondition: true,
    attrs: { type_aide: '{typeAttr}' },
    opts: { aide: ['Prêt de matériel de bricolage', 'Aide informatique aux seniors'], typeAttr: ['Prêt de matériel', 'Informatique'], texte: ['Je prête volontiers perceuse, ponceuse, échelle et taille-haie aux voisins du quartier.', 'Je viens vous aider à configurer votre téléphone, votre ordinateur ou votre box, et je vous explique sans jargon.'], dispo: ['le week-end', 'en fin de journée'] },
    pair: { aide: 'typeAttr', aide2: 'texte' },
    q: ['neighbors helping tools', 'helping senior with computer'], qByOpt: 'aide', photos: [2, 2],
  }),
  V('billetterie', 2, {
    title: '{nb} places {evenement}, {date}',
    desc: '{nb} places pour {evenement} le {date}, {categorie}. Billets nominatifs transférables via la billetterie officielle, je fais le changement de nom avec vous. Vendues au prix d\'achat, empêchement de dernière minute.',
    price: [45, 120], noCondition: true,
    attrs: { type_billet: '{typeAttr}', date_evenement: '{date}' },
    opts: { nb: [2, 2], evenement: ['un concert de rock à l\'Arena', 'un match de Top 14'], typeAttr: ['Concert', 'Sport'], date: ['14 novembre 2026', '28 novembre 2026'], categorie: ['catégorie 2, placées', 'tribune latérale'] },
    pair: { evenement: 'typeAttr', evenement2: 'date', evenement3: 'categorie' },
    q: ['concert crowd stage lights', 'rugby stadium match'], qByOpt: 'evenement', photos: [2, 2],
  }),
];
