import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialPostgres1789255931367 implements MigrationInterface {
    name = 'InitialPostgres1789255931367'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "phoneNumber" character varying NOT NULL, "phoneVerified" boolean NOT NULL DEFAULT false, "email" character varying, "displayName" character varying NOT NULL, "avatarUrl" character varying, "accountType" character varying NOT NULL DEFAULT 'particulier', "city" character varying, "postalCode" character varying, "latitude" double precision, "longitude" double precision, "shopName" character varying, "shopDescription" text, "shopLogoUrl" character varying, "shopAddress" character varying, "shopHours" character varying, "shopWebsite" character varying, "siret" character varying, "stripeAccountId" character varying, "stripeOnboardingComplete" boolean NOT NULL DEFAULT false, "ratingAvg" double precision NOT NULL DEFAULT '0', "ratingCount" integer NOT NULL DEFAULT '0', "identityVerified" boolean NOT NULL DEFAULT false, "notifyPush" boolean NOT NULL DEFAULT true, "notifySms" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "suspendedAt" TIMESTAMP WITH TIME ZONE, "suspensionReason" text, "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_1e3d0240b49c40521aaeb953293" UNIQUE ("phoneNumber"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e456a497674a1886ddbdc93228" ON "users" ("accountType") `);
        await queryRunner.query(`CREATE TABLE "user_blocks" ("blockerId" character varying NOT NULL, "blockedId" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_fc74151c76df192714f76b2a2e1" PRIMARY KEY ("blockerId", "blockedId"))`);
        await queryRunner.query(`CREATE TABLE "shop_members" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "ownerId" character varying NOT NULL, "memberId" character varying NOT NULL, "role" character varying NOT NULL DEFAULT 'gestionnaire', "invitedBy" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5935c3cb1290b7c356cb72e97cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ca56955241c85f346713c798ed" ON "shop_members" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_84672f038e729641dd0ad43fef" ON "shop_members" ("memberId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_42007ca41ad29e4a0517dd5b53" ON "shop_members" ("ownerId", "memberId") `);
        await queryRunner.query(`CREATE TABLE "system_settings" ("key" character varying NOT NULL, "value" text NOT NULL, "updatedBy" character varying, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b1b5bc664526d375c94ce9ad43d" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "userId" character varying NOT NULL, "planId" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'active', "provider" character varying, "providerRef" character varying, "startedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "endsAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fbdba4e2ac694cf8c9cecf4dc8" ON "subscriptions" ("userId") `);
        await queryRunner.query(`CREATE TABLE "plans" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "description" text, "priceMonthly" double precision NOT NULL DEFAULT '0', "listingsIncluded" integer, "boostsIncluded" integer, "advancedStats" boolean NOT NULL DEFAULT false, "verifiedBadge" boolean NOT NULL DEFAULT false, "customShop" boolean NOT NULL DEFAULT false, "active" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_e7b71bb444e74ee067df057397e" UNIQUE ("slug"), CONSTRAINT "PK_3720521a81c7c24fe9b7202ba61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "saved_searches" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "userId" character varying NOT NULL, "name" character varying(80) NOT NULL, "query" text NOT NULL, "notifyPush" boolean NOT NULL DEFAULT true, "notifySms" boolean NOT NULL DEFAULT false, "lastCheckedAt" TIMESTAMP WITH TIME ZONE, "matchesNotified" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d9a53c71ccc5cf66dcdc5b33dfe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_507a6228007bed5e89b3a29157" ON "saved_searches" ("userId") `);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "listingId" character varying NOT NULL, "buyerId" character varying NOT NULL, "sellerId" character varying NOT NULL, "amount" double precision NOT NULL, "commission" double precision NOT NULL, "buyerFee" double precision NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'en_attente', "deliveryMethod" character varying NOT NULL DEFAULT 'main_propre', "providerPaymentId" character varying, "deliveryTrackingNumber" character varying, "handoverCode" character varying, "disputeReason" text, "disputeOpenedBy" character varying, "resolutionNote" text, "shippedAt" TIMESTAMP WITH TIME ZONE, "confirmedAt" TIMESTAMP WITH TIME ZONE, "resolvedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1908fc98d7a21e27a3ea709fa8" ON "transactions" ("listingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ec4767e5beacbc7dfaa507d1fc" ON "transactions" ("buyerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5848e57fcb8971eeb768c3a6b4" ON "transactions" ("sellerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_da87c55b3bbbe96c6ed88ea7ee" ON "transactions" ("status") `);
        await queryRunner.query(`CREATE TABLE "phone_verifications" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "phoneNumber" character varying NOT NULL, "codeHash" character varying NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "attempts" integer NOT NULL DEFAULT '0', "verifiedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_11ef2c1c5ed828b9636472db666" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e5410ab84bfc47b4aca5e2a6a0" ON "phone_verifications" ("phoneNumber") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "userId" character varying NOT NULL, "type" character varying NOT NULL, "title" character varying NOT NULL, "body" text, "link" character varying, "readAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_692a909ee0fa9383e7859f9b40" ON "notifications" ("userId") `);
        await queryRunner.query(`CREATE TABLE "listings" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "userId" character varying NOT NULL, "createdBy" character varying, "categoryId" integer NOT NULL, "rootCategoryId" integer, "title" character varying(150) NOT NULL, "description" text NOT NULL, "price" double precision, "priceType" character varying NOT NULL DEFAULT 'fixe', "condition" character varying, "status" character varying NOT NULL DEFAULT 'en_ligne', "moderationReason" text, "attributes" text, "city" character varying, "postalCode" character varying, "latitude" double precision, "longitude" double precision, "deliveryAvailable" boolean NOT NULL DEFAULT false, "viewsCount" integer NOT NULL DEFAULT '0', "boostedUntil" TIMESTAMP WITH TIME ZONE, "urgentUntil" TIMESTAMP WITH TIME ZONE, "externalRef" character varying, "publishedAt" TIMESTAMP WITH TIME ZONE, "expiresAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_520ecac6c99ec90bcf5a603cdcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_45d5c4642c4cad0229da0ec22e" ON "listings" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ec7707e3d6ac9f84f24a6baee4" ON "listings" ("categoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_efaba7f2bd68faee2e5a2068cd" ON "listings" ("rootCategoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0a65b771bc8228047f2f78a091" ON "listings" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_80fe4ae7e4b503c4ab9b2fa6fe" ON "listings" ("postalCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_b20884d8460486828628e38a3d" ON "listings" ("boostedUntil") `);
        await queryRunner.query(`CREATE INDEX "IDX_673e98815014b22792c173910e" ON "listings" ("expiresAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ea780830bbafe57b989eb132cd" ON "listings" ("userId", "externalRef") WHERE "externalRef" IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "listing_views" ("userId" character varying NOT NULL, "listingId" character varying NOT NULL, "viewedAt" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_428adb4768096dcbbfaaaef533e" PRIMARY KEY ("userId", "listingId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5619518f38f41813da16e47288" ON "listing_views" ("viewedAt") `);
        await queryRunner.query(`CREATE TABLE "listing_photos" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "listingId" character varying NOT NULL, "url" character varying NOT NULL, "sortOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_73c5fd7f964a698b78f0920917c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fbe5bfb140ed07ab1bc04bd92c" ON "listing_photos" ("listingId") `);
        await queryRunner.query(`CREATE TABLE "favorites" ("userId" character varying NOT NULL, "listingId" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d444e30d3b67e3dcfdd47402fe0" PRIMARY KEY ("userId", "listingId"))`);
        await queryRunner.query(`CREATE TABLE "legal_pages" ("slug" character varying NOT NULL, "title" character varying NOT NULL, "content" text NOT NULL, "published" boolean NOT NULL DEFAULT true, "updatedBy" character varying, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f1f163cfa770af83882769be571" PRIMARY KEY ("slug"))`);
        await queryRunner.query(`CREATE TABLE "reports" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "reporterId" character varying NOT NULL, "listingId" character varying, "reportedUserId" character varying, "conversationId" character varying, "reason" character varying NOT NULL, "details" text, "status" character varying NOT NULL DEFAULT 'ouvert', "handledBy" character varying, "resolutionNote" text, "handledAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4353be8309ce86650def2f8572" ON "reports" ("reporterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a10deac46782374ec9f01b8901" ON "reports" ("listingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c88d2686339ad6d166620b741a" ON "reports" ("reportedUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_dab4d78b3be05c1ca4a626f57f" ON "reports" ("status") `);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "conversationId" character varying NOT NULL, "senderId" character varying NOT NULL, "type" character varying NOT NULL DEFAULT 'text', "content" text, "attachmentUrl" character varying, "offerAmount" double precision, "offerStatus" character varying, "readAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e5663ce0c730b2de83445e2fd1" ON "messages" ("conversationId") `);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "transactionId" character varying NOT NULL, "reviewerId" character varying NOT NULL, "reviewedId" character varying NOT NULL, "rating" integer NOT NULL, "comment" text, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "conversations" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "listingId" character varying NOT NULL, "buyerId" character varying NOT NULL, "sellerId" character varying NOT NULL, "lastMessageAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ee34f4f7ced4ec8681f26bf04ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a82a38c758dadc667a5565b42c" ON "conversations" ("listingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fad7b384e73ce2b5e9029a0032" ON "conversations" ("buyerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4173670d70b706461e31d847ce" ON "conversations" ("sellerId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6f89644a7bb43adc006fb8fc6a" ON "conversations" ("listingId", "buyerId") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "userId" character varying NOT NULL, "tokenHash" character varying NOT NULL, "familyId" character varying NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "revokedAt" TIMESTAMP WITH TIME ZONE, "replacedById" character varying, "userAgent" character varying, "ip" character varying, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_610102b60fea1455310ccd299d" ON "refresh_tokens" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c25bc63d248ca90e8dcc1d92d0" ON "refresh_tokens" ("tokenHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_40e9a8b923a1b3fb4429a5c624" ON "refresh_tokens" ("familyId") `);
        await queryRunner.query(`CREATE TABLE "admin_audit_log" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "adminId" character varying NOT NULL, "action" character varying NOT NULL, "targetType" character varying NOT NULL, "targetId" character varying NOT NULL, "details" text, "ip" character varying, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_9425be48a9c753f5753017c61b2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8fa8f152c0c4b077ff5fc4262b" ON "admin_audit_log" ("adminId") `);
        await queryRunner.query(`CREATE INDEX "IDX_660bcad1f33a1fc991c21404f0" ON "admin_audit_log" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_6753d9e4b1679bce4ad0dac824" ON "admin_audit_log" ("targetId") `);
        await queryRunner.query(`CREATE TABLE "categories" ("id" SERIAL NOT NULL, "parentId" integer, "slug" character varying NOT NULL, "name" character varying NOT NULL, "icon" character varying, "sortOrder" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_420d9f679d41281f282f5bc7d09" UNIQUE ("slug"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9a6f051e66982b5f0318981bca" ON "categories" ("parentId") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_9a6f051e66982b5f0318981bca"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6753d9e4b1679bce4ad0dac824"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_660bcad1f33a1fc991c21404f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8fa8f152c0c4b077ff5fc4262b"`);
        await queryRunner.query(`DROP TABLE "admin_audit_log"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40e9a8b923a1b3fb4429a5c624"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c25bc63d248ca90e8dcc1d92d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_610102b60fea1455310ccd299d"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f89644a7bb43adc006fb8fc6a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4173670d70b706461e31d847ce"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fad7b384e73ce2b5e9029a0032"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a82a38c758dadc667a5565b42c"`);
        await queryRunner.query(`DROP TABLE "conversations"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5663ce0c730b2de83445e2fd1"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dab4d78b3be05c1ca4a626f57f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c88d2686339ad6d166620b741a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a10deac46782374ec9f01b8901"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4353be8309ce86650def2f8572"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TABLE "legal_pages"`);
        await queryRunner.query(`DROP TABLE "favorites"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fbe5bfb140ed07ab1bc04bd92c"`);
        await queryRunner.query(`DROP TABLE "listing_photos"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5619518f38f41813da16e47288"`);
        await queryRunner.query(`DROP TABLE "listing_views"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ea780830bbafe57b989eb132cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_673e98815014b22792c173910e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b20884d8460486828628e38a3d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_80fe4ae7e4b503c4ab9b2fa6fe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a65b771bc8228047f2f78a091"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_efaba7f2bd68faee2e5a2068cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ec7707e3d6ac9f84f24a6baee4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45d5c4642c4cad0229da0ec22e"`);
        await queryRunner.query(`DROP TABLE "listings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_692a909ee0fa9383e7859f9b40"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5410ab84bfc47b4aca5e2a6a0"`);
        await queryRunner.query(`DROP TABLE "phone_verifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da87c55b3bbbe96c6ed88ea7ee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5848e57fcb8971eeb768c3a6b4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ec4767e5beacbc7dfaa507d1fc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1908fc98d7a21e27a3ea709fa8"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_507a6228007bed5e89b3a29157"`);
        await queryRunner.query(`DROP TABLE "saved_searches"`);
        await queryRunner.query(`DROP TABLE "plans"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fbdba4e2ac694cf8c9cecf4dc8"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TABLE "system_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_42007ca41ad29e4a0517dd5b53"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_84672f038e729641dd0ad43fef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca56955241c85f346713c798ed"`);
        await queryRunner.query(`DROP TABLE "shop_members"`);
        await queryRunner.query(`DROP TABLE "user_blocks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e456a497674a1886ddbdc93228"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
